import pprint
names = [
    "ContextMgmt_param_fdir_sw_1v5c_min", "ContextMgmt_param_fdir_sw_1v5c_max",
    "ContextMgmt_param_fdir_hw_1v5c", "ContextMgmt_param_fdir_sw_2v5c_min",
    "ContextMgmt_param_fdir_sw_2v5c_max", "ContextMgmt_param_fdir_hw_2v5c",
    "ContextMgmt_param_fdir_sw_3v3c_min", "ContextMgmt_param_fdir_sw_3v3c_max",
    "ContextMgmt_param_fdir_hw_3v3c", "ContextMgmt_param_fdir_sw_spw0c_min",
    "ContextMgmt_param_fdir_sw_spw0c_max",
    "ContextMgmt_param_fdir_sw_spw1c_min",
    "ContextMgmt_param_fdir_sw_spw1c_max",
    "ContextMgmt_param_fdir_sw_spw2c_min",
    "ContextMgmt_param_fdir_sw_spw2c_max", "ContextMgmt_param_fdir_hw_spwc",
    "ContextMgmt_param_fdir_sw_det0c_min",
    "ContextMgmt_param_fdir_sw_det0c_max",
    "ContextMgmt_param_fdir_sw_det1c_min",
    "ContextMgmt_param_fdir_sw_det1c_max",
    "ContextMgmt_param_fdir_sw_det2c_min",
    "ContextMgmt_param_fdir_sw_det2c_max",
    "ContextMgmt_param_fdir_sw_det3c_min",
    "ContextMgmt_param_fdir_sw_det3c_max",
    "ContextMgmt_param_fdir_sw_det4c_min",
    "ContextMgmt_param_fdir_sw_det4c_max", "ContextMgmt_param_fdir_hw_detc",
    "ContextMgmt_param_fdir_sw_att0c_min",
    "ContextMgmt_param_fdir_sw_att0c_max",
    "ContextMgmt_param_fdir_sw_att1c_min",
    "ContextMgmt_param_fdir_sw_att1c_max",
    "ContextMgmt_param_fdir_sw_att2c_min",
    "ContextMgmt_param_fdir_sw_att2c_max", "ContextMgmt_param_fdir_hw_attc",
    "ContextMgmt_param_fdir_sw_attv_min", "ContextMgmt_param_fdir_sw_attv_max",
    "ContextMgmt_param_fdir_hw_attv", "ContextMgmt_param_fdir_sw_hw01_min",
    "ContextMgmt_param_fdir_sw_hw01_max", "ContextMgmt_param_fdir_hw_hw01",
    "ContextMgmt_param_fdir_sw_hw02_min", "ContextMgmt_param_fdir_sw_hw02_max",
    "ContextMgmt_param_fdir_hw_hw02", "ContextMgmt_param_fdir_sw_2v9v_min",
    "ContextMgmt_param_fdir_sw_2v9v_max", "ContextMgmt_param_fdir_sw_2v5v_min",
    "ContextMgmt_param_fdir_sw_2v5v_max", "ContextMgmt_param_fdir_sw_1v5v_min",
    "ContextMgmt_param_fdir_sw_1v5v_max",
    "ContextMgmt_param_fdir_sw_spw0v_min",
    "ContextMgmt_param_fdir_sw_spw0v_max",
    "ContextMgmt_param_fdir_sw_spw1v_min",
    "ContextMgmt_param_fdir_sw_spw1v_max",
    "ContextMgmt_param_fdir_sw_asp_vsensa_min",
    "ContextMgmt_param_fdir_sw_asp_vsensa_max",
    "ContextMgmt_param_fdir_sw_asp_vsensb_min",
    "ContextMgmt_param_fdir_sw_asp_vsensb_max",
    "ContextMgmt_param_fdir_sw_asp_refa_min",
    "ContextMgmt_param_fdir_sw_asp_refa_max",
    "ContextMgmt_param_fdir_sw_asp_refb_min",
    "ContextMgmt_param_fdir_sw_asp_refb_max",
    "ContextMgmt_param_fdir_sw_asp_photoA0_min",
    "ContextMgmt_param_fdir_sw_asp_photoA0_max",
    "ContextMgmt_param_fdir_sw_asp_photoA1_min",
    "ContextMgmt_param_fdir_sw_asp_photoA1_max",
    "ContextMgmt_param_fdir_sw_asp_photoB0_min",
    "ContextMgmt_param_fdir_sw_asp_photoB0_max",
    "ContextMgmt_param_fdir_sw_asp_photoB1_min",
    "ContextMgmt_param_fdir_sw_asp_photoB1_max",
    "ContextMgmt_param_fdir_sw_fpgat_min",
    "ContextMgmt_param_fdir_sw_fpgat_max",
    "ContextMgmt_param_fdir_sw_pcbt_min", "ContextMgmt_param_fdir_sw_pcbt_max",
    "ContextMgmt_param_fdir_sw_tim01t_min",
    "ContextMgmt_param_fdir_sw_tim01t_max",
    "ContextMgmt_param_fdir_sw_tim02t_min",
    "ContextMgmt_param_fdir_sw_tim02t_max",
    "ContextMgmt_param_fdir_sw_tim03t_min",
    "ContextMgmt_param_fdir_sw_tim03t_max",
    "ContextMgmt_param_fdir_sw_tim04t_min",
    "ContextMgmt_param_fdir_sw_tim04t_max",
    "ContextMgmt_param_fdir_sw_tim05t_min",
    "ContextMgmt_param_fdir_sw_tim05t_max",
    "ContextMgmt_param_fdir_sw_tim06t_min",
    "ContextMgmt_param_fdir_sw_tim06t_max",
    "ContextMgmt_param_fdir_sw_tim07t_min",
    "ContextMgmt_param_fdir_sw_tim07t_max",
    "ContextMgmt_param_fdir_sw_tim08t_min",
    "ContextMgmt_param_fdir_sw_tim08t_max",
    "ContextMgmt_param_fdir_sw_det01t_min",
    "ContextMgmt_param_fdir_sw_det01t_max",
    "ContextMgmt_param_fdir_sw_det02t_min",
    "ContextMgmt_param_fdir_sw_det02t_max",
    "ContextMgmt_param_fdir_sw_det03t_min",
    "ContextMgmt_param_fdir_sw_det03t_max",
    "ContextMgmt_param_fdir_sw_det04t_min",
    "ContextMgmt_param_fdir_sw_det04t_max",
    "ContextMgmt_param_fdir_sw_attt_min", "ContextMgmt_param_fdir_sw_attt_max",
    "ContextMgmt_param_fdir_meas_trig_psut",
    "ContextMgmt_param_fdir_meas_trig_pcbt",
    "ContextMgmt_param_fdir_meas_trig_fpgat",
    "ContextMgmt_param_fdir_meas_trig_3v3c",
    "ContextMgmt_param_fdir_meas_trig_2v5c",
    "ContextMgmt_param_fdir_meas_trig_1v5c",
    "ContextMgmt_param_fdir_meas_trig_spwc",
    "ContextMgmt_param_fdir_meas_trig_spw0v",
    "ContextMgmt_param_fdir_meas_trig_spw1v",
    "ContextMgmt_param_fdir_meas_trig_1v5v",
    "ContextMgmt_param_fdir_meas_trig_2v5v",
    "ContextMgmt_param_fdir_meas_trig_2v9v",
    "ContextMgmt_param_fdir_meas_trig_attv",
    "ContextMgmt_param_fdir_meas_trig_attc",
    "ContextMgmt_param_fdir_meas_trig_attt",
    "ContextMgmt_param_fdir_meas_trig_hv01",
    "ContextMgmt_param_fdir_meas_trig_hv02",
    "ContextMgmt_param_fdir_meas_trig_detc",
    "ContextMgmt_param_fdir_meas_trig_detq1t",
    "ContextMgmt_param_fdir_meas_trig_detq2t",
    "ContextMgmt_param_fdir_meas_trig_detq3t",
    "ContextMgmt_param_fdir_meas_trig_detq4t",
    "ContextMgmt_param_fdir_meas_trig_asp_refa",
    "ContextMgmt_param_fdir_meas_trig_asp_refb",
    "ContextMgmt_param_fdir_meas_trig_tim01t",
    "ContextMgmt_param_fdir_meas_trig_tim02t",
    "ContextMgmt_param_fdir_meas_trig_tim03t",
    "ContextMgmt_param_fdir_meas_trig_tim04t",
    "ContextMgmt_param_fdir_meas_trig_tim05t",
    "ContextMgmt_param_fdir_meas_trig_tim06t",
    "ContextMgmt_param_fdir_meas_trig_tim07t",
    "ContextMgmt_param_fdir_meas_trig_tim08t",
    "ContextMgmt_param_fdir_meas_trig_asp_vsensa",
    "ContextMgmt_param_fdir_meas_trig_asp_vsensb",
    "ContextMgmt_param_fdir_meas_trig_asp_photoa0",
    "ContextMgmt_param_fdir_meas_trig_asp_photoa1",
    "ContextMgmt_param_fdir_meas_trig_asp_photob0",
    "ContextMgmt_param_fdir_meas_trig_asp_photob1",
    "ContextMgmt_param_fdir_seu_ignore_flag",
    "ContextMgmt_param_fdir_enabled_dete_quarter",
    "ContextMgmt_param_fdir_att_number_moves", "ContextMgmt_param_fdir_att_N1",
    "ContextMgmt_param_fdir_att_T1", "ContextMgmt_param_fdir_att_N2",
    "ContextMgmt_param_fdir_att_T2",
    "ContextMgmt_param_fdir_asic_verif_disabled_dete_mask",
    "ContextMgmt_param_fdir_asic_verif_period",
    "ContextMgmt_param_fdir_hv01_depolarisation_period",
    "ContextMgmt_param_fdir_hv02_depolarisation_period",
    "ContextMgmt_param_fdir_hv01_depolarisation_duration",
    "ContextMgmt_param_fdir_hv02_depolarisation_duration",
    "ContextMgmt_param_fdir_enabled_function_mask",
    "ContextMgmt_param_fdir_enabled_current_function_checks",
    "ContextMgmt_param_fdir_enabled_voltage_function_checks",
    "ContextMgmt_param_fdir_enabled_temperature_function_checks",
    "ContextMgmt_param_config_hv01_line_enabled",
    "ContextMgmt_param_config_hv02_line_enabled",
    "ContextMgmt_param_config_hv01_value",
    "ContextMgmt_param_config_hv02_value",
    "ContextMgmt_param_config_spw_ocp_state",
    "ContextMgmt_param_config_det_ocp_state",
    "ContextMgmt_param_config_att_ocp_state",
    "ContextMgmt_param_config_1v5_ocp_state",
    "ContextMgmt_param_config_2v5_ocp_state",
    "ContextMgmt_param_config_3v3_ocp_state",
    "ContextMgmt_param_config_att_ovp_state",
    "ContextMgmt_param_config_hv1_ovp_state",
    "ContextMgmt_param_config_hv2_ovp_state",
    "ContextMgmt_param_config_asp_fpga_readout_per_sum",
    "ContextMgmt_param_config_att_max_pwm",
    "ContextMgmt_param_config_att_nom_pwm",
    "ContextMgmt_param_config_fsw_s20_reaction_state",
    "ContextMgmt_param_config_fsw_enable_tm51",
    "ContextMgmt_param_config_sdram_prescaler",
    "ContextMgmt_param_config_rotb_prescaler",
    "ContextMgmt_param_config_spw_transient_duration",
    "ContextMgmt_param_calib_cyclic_state", "ContextMgmt_param_calib_tq",
    "ContextMgmt_param_calib_detemask", "ContextMgmt_param_calib_ta",
    "ContextMgmt_param_calib_formatting_subspectra_mask",
    "ContextMgmt_param_calib_formatting_subspectrum_1",
    "ContextMgmt_param_calib_formatting_subspectrum_2",
    "ContextMgmt_param_calib_formatting_subspectrum_3",
    "ContextMgmt_param_calib_formatting_subspectrum_4",
    "ContextMgmt_param_calib_formatting_subspectrum_5",
    "ContextMgmt_param_calib_formatting_subspectrum_6",
    "ContextMgmt_param_calib_formatting_subspectrum_7",
    "ContextMgmt_param_calib_formatting_subspectrum_8",
    "ContextMgmt_param_calib_formatting_detemask",
    "ContextMgmt_param_calib_formatting_bit_reduction_flag",
    "ContextMgmt_param_calib_formatting_pixelmask",
    "ContextMgmt_param_ql_nominal_period", "ContextMgmt_param_qlbg_enabled",
    "ContextMgmt_param_qlbg_enabled_tm",
    "ContextMgmt_param_qlbg_default_value_range_1",
    "ContextMgmt_param_qlbg_default_value_range_2",
    "ContextMgmt_param_qlbg_default_value_range_3",
    "ContextMgmt_param_qlbg_default_value_range_4",
    "ContextMgmt_param_qlbg_default_value_range_5",
    "ContextMgmt_param_qlbg_default_value_range_6",
    "ContextMgmt_param_qlbg_default_value_range_7",
    "ContextMgmt_param_qlbg_default_value_range_8",
    "ContextMgmt_param_qlbg_ql_integration_per_datum",
    "ContextMgmt_param_qlbg_compression_scheme_counts",
    "ContextMgmt_param_qlbg_compression_scheme_triggers",
    "ContextMgmt_param_qlbg_energy_bin_edge_mask_upper_bit",
    "ContextMgmt_param_qlbg_energy_bin_edge_mask_lower_bits",
    "ContextMgmt_param_qllc_energy_bin_edge_mask_upper_bit",
    "ContextMgmt_param_qllc_energy_bin_edge_mask_lower_bits",
    "ContextMgmt_param_qllc_enable_tm",
    "ContextMgmt_param_qllc_ql_integration_per_datum",
    "ContextMgmt_param_qllc_compression_scheme_counts",
    "ContextMgmt_param_qllc_compression_scheme_triggers",
    "ContextMgmt_param_qllc_detemask", "ContextMgmt_param_qllc_pixemask",
    "ContextMgmt_param_qlfdet_pixemask",
    "ContextMgmt_param_qlfdet_thermal_energy_mask",
    "ContextMgmt_param_qlfdet_nonthermal_energy_mask",
    "ContextMgmt_param_qlfdet_kb",
    "ContextMgmt_param_qlfdet_thermal_factor_rcr1",
    "ContextMgmt_param_qlfdet_thermal_factor_rcr2",
    "ContextMgmt_param_qlfdet_thermal_factor_rcr3",
    "ContextMgmt_param_qlfdet_thermal_factor_rcr4",
    "ContextMgmt_param_qlfdet_thermal_factor_rcr5",
    "ContextMgmt_param_qlfdet_thermal_factor_rcr6",
    "ContextMgmt_param_qlfdet_thermal_factor_rcr7",
    "ContextMgmt_param_qlfdet_thermal_factor_rcr8",
    "ContextMgmt_param_qlfdet_nonthermal_factor_rcr1",
    "ContextMgmt_param_qlfdet_nonthermal_factor_rcr2",
    "ContextMgmt_param_qlfdet_nonthermal_factor_rcr3",
    "ContextMgmt_param_qlfdet_nonthermal_factor_rcr4",
    "ContextMgmt_param_qlfdet_nonthermal_factor_rcr5",
    "ContextMgmt_param_qlfdet_nonthermal_factor_rcr6",
    "ContextMgmt_param_qlfdet_nonthermal_factor_rcr7",
    "ContextMgmt_param_qlfdet_nonthermal_factor_rcr8",
    "ContextMgmt_param_qlfdet_k", "ContextMgmt_param_qlfdet_kp",
    "ContextMgmt_param_qlfdet_kpp", "ContextMgmt_param_qlfdet_timescale_short",
    "ContextMgmt_param_qlfdet_timescale_long",
    "ContextMgmt_param_qlfdet_init_thermal_cbc",
    "ContextMgmt_param_qlfdet_init_nonthermal_cbc",
    "ContextMgmt_param_qlfdet_cfmin",
    "ContextMgmt_param_qlfdet_threshold_thermal_B1",
    "ContextMgmt_param_qlfdet_threshold_thermal_C1",
    "ContextMgmt_param_qlfdet_threshold_thermal_M1",
    "ContextMgmt_param_qlfdet_threshold_thermal_X1",
    "ContextMgmt_param_qlfdet_threshold_nonthermal_weak",
    "ContextMgmt_param_qlfdet_threshold_nonthermal_significant",
    "ContextMgmt_param_qlfdetfloc_enable_tm",
    "ContextMgmt_param_qlfdet_ql_integration_per_datum",
    "ContextMgmt_param_qlffloc_ql_integration_per_datum",
    "ContextMgmt_param_qlfloc_dete_mask",
    "ContextMgmt_param_qlfloc_energy_mask",
    "ContextMgmt_param_qlfloc_sky_table_id", "ContextMgmt_param_qlfloc_L1",
    "ContextMgmt_param_qlfloc_L2", "ContextMgmt_param_qlfloc_k",
    "ContextMgmt_param_qlfloc_kp", "ContextMgmt_param_qlfloc_kpp",
    "ContextMgmt_param_qlfloc_kppp", "ContextMgmt_param_qlfloc_k0",
    "ContextMgmt_param_qlfloc_k1", "ContextMgmt_param_qlfloc_k2",
    "ContextMgmt_param_qlfloc_dx", "ContextMgmt_param_qlfloc_dy",
    "ContextMgmt_param_qldmon_active_detector_mask",
    "ContextMgmt_param_qldmon_energy_mask",
    "ContextMgmt_param_qldmon_ql_integration_per_datum",
    "ContextMgmt_param_qldmon_kbad", "ContextMgmt_param_qldmon_rbad",
    "ContextMgmt_param_qldmon_nbad", "ContextMgmt_param_qldmon_nrep",
    "ContextMgmt_param_qlsp_detemask", "ContextMgmt_param_qlsp_pixemask",
    "ContextMgmt_param_qlsp_ql_integrations_per_datum",
    "ContextMgmt_param_qlsp_enable_tm",
    "ContextMgmt_param_qlsp_compression_scheme_counts",
    "ContextMgmt_param_qlsp_compression_scheme_triggers",
    "ContextMgmt_param_qlvar_detemask", "ContextMgmt_param_qlvar_enemask",
    "ContextMgmt_param_qlvar_pixemask", "ContextMgmt_param_qlvar_enable_tm",
    "ContextMgmt_param_qlvar_compression_scheme_counts",
    "ContextMgmt_param_qlrcr_enabled", "ContextMgmt_param_qlrcr_group_mask",
    "ContextMgmt_param_qlrcr_pixelmask_rcr0",
    "ContextMgmt_param_qlrcr_pixelmask_rcr1",
    "ContextMgmt_param_qlrcr_pixelmask_rcr2_north",
    "ContextMgmt_param_qlrcr_pixelmask_rcr2_south",
    "ContextMgmt_param_qlrcr_pixelmask_rcr3_north_1",
    "ContextMgmt_param_qlrcr_pixelmask_rcr3_north_2",
    "ContextMgmt_param_qlrcr_pixelmask_rcr3_south_1",
    "ContextMgmt_param_qlrcr_pixelmask_rcr3_south_2",
    "ContextMgmt_param_qlrcr_pixelmask_rcr4_north_1",
    "ContextMgmt_param_qlrcr_pixelmask_rcr4_north_2",
    "ContextMgmt_param_qlrcr_pixelmask_rcr4_north_3",
    "ContextMgmt_param_qlrcr_pixelmask_rcr4_north_4",
    "ContextMgmt_param_qlrcr_pixelmask_rcr4_south_1",
    "ContextMgmt_param_qlrcr_pixelmask_rcr4_south_2",
    "ContextMgmt_param_qlrcr_pixelmask_rcr4_south_3",
    "ContextMgmt_param_qlrcr_pixelmask_rcr4_south_4",
    "ContextMgmt_param_qlrcr_pixelmask_rcr5",
    "ContextMgmt_param_qlrcr_pixelmask_rcr6_1",
    "ContextMgmt_param_qlrcr_pixelmask_rcr6_2",
    "ContextMgmt_param_qlrcr_pixelmask_rcr7_1",
    "ContextMgmt_param_qlrcr_pixelmask_rcr7_2",
    "ContextMgmt_param_qlrcr_pixelmask_rcr7_3",
    "ContextMgmt_param_qlrcr_pixelmask_rcr7_4",
    "ContextMgmt_param_qlrcr_regime2state_lut",
    "ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr0",
    "ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr1",
    "ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr2",
    "ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr3",
    "ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr4",
    "ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr5",
    "ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr6",
    "ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr7",
    "ContextMgmt_param_qlrcr_L0", "ContextMgmt_param_qlrcr_L1",
    "ContextMgmt_param_qlrcr_L2", "ContextMgmt_param_qlrcr_L3",
    "ContextMgmt_param_accum_max_duration",
    "ContextMgmt_param_accum_min_duration",
    "ContextMgmt_param_accum_max_counts", "ContextMgmt_param_accum_sum_e_mask",
    "ContextMgmt_param_accum_sum_d_mask", "ContextMgmt_param_data_level",
    "ContextMgmt_param_data_l0_dete_mask",
    "ContextMgmt_param_data_l0_pixe_mask",
    "ContextMgmt_param_data_l1_rcr1_pixe_mask",
    "ContextMgmt_param_data_l1_rcr2_pixe_mask",
    "ContextMgmt_param_data_l1_rcr3_pixe_mask",
    "ContextMgmt_param_data_l1_rcr4_pixe_mask",
    "ContextMgmt_param_data_l1_rcr5_pixe_mask",
    "ContextMgmt_param_data_l1_rcr6_pixe_mask",
    "ContextMgmt_param_data_l1_rcr7_pixe_mask",
    "ContextMgmt_param_data_l1_rcr8_pixe_mask",
    "ContextMgmt_param_data_l2_rcr1_pixe_mask1",
    "ContextMgmt_param_data_l2_rcr1_pixe_mask2",
    "ContextMgmt_param_data_l2_rcr1_pixe_mask3",
    "ContextMgmt_param_data_l2_rcr1_pixe_mask4",
    "ContextMgmt_param_data_l2_rcr1_pixe_mask5",
    "ContextMgmt_param_data_l2_rcr2_pixe_mask1",
    "ContextMgmt_param_data_l2_rcr2_pixe_mask2",
    "ContextMgmt_param_data_l2_rcr2_pixe_mask3",
    "ContextMgmt_param_data_l2_rcr2_pixe_mask4",
    "ContextMgmt_param_data_l2_rcr2_pixe_mask5",
    "ContextMgmt_param_data_l2_rcr3_pixe_mask1",
    "ContextMgmt_param_data_l2_rcr3_pixe_mask2",
    "ContextMgmt_param_data_l2_rcr3_pixe_mask3",
    "ContextMgmt_param_data_l2_rcr3_pixe_mask4",
    "ContextMgmt_param_data_l2_rcr3_pixe_mask5",
    "ContextMgmt_param_data_l2_rcr4_pixe_mask1",
    "ContextMgmt_param_data_l2_rcr4_pixe_mask2",
    "ContextMgmt_param_data_l2_rcr4_pixe_mask3",
    "ContextMgmt_param_data_l2_rcr4_pixe_mask4",
    "ContextMgmt_param_data_l2_rcr4_pixe_mask5",
    "ContextMgmt_param_data_l2_rcr5_pixe_mask1",
    "ContextMgmt_param_data_l2_rcr5_pixe_mask2",
    "ContextMgmt_param_data_l2_rcr5_pixe_mask3",
    "ContextMgmt_param_data_l2_rcr5_pixe_mask4",
    "ContextMgmt_param_data_l2_rcr5_pixe_mask5",
    "ContextMgmt_param_data_l2_rcr6_pixe_mask1",
    "ContextMgmt_param_data_l2_rcr6_pixe_mask2",
    "ContextMgmt_param_data_l2_rcr6_pixe_mask3",
    "ContextMgmt_param_data_l2_rcr6_pixe_mask4",
    "ContextMgmt_param_data_l2_rcr6_pixe_mask5",
    "ContextMgmt_param_data_l2_rcr7_pixe_mask1",
    "ContextMgmt_param_data_l2_rcr7_pixe_mask2",
    "ContextMgmt_param_data_l2_rcr7_pixe_mask3",
    "ContextMgmt_param_data_l2_rcr7_pixe_mask4",
    "ContextMgmt_param_data_l2_rcr7_pixe_mask5",
    "ContextMgmt_param_data_l2_rcr8_pixe_mask1",
    "ContextMgmt_param_data_l2_rcr8_pixe_mask2",
    "ContextMgmt_param_data_l2_rcr8_pixe_mask3",
    "ContextMgmt_param_data_l2_rcr8_pixe_mask4",
    "ContextMgmt_param_data_l2_rcr8_pixe_mask5",
    "ContextMgmt_param_data_l3_rcr1_pixe_mask1",
    "ContextMgmt_param_data_l3_rcr1_pixe_mask2",
    "ContextMgmt_param_data_l3_rcr1_pixe_mask3",
    "ContextMgmt_param_data_l3_rcr1_pixe_mask4",
    "ContextMgmt_param_data_l3_rcr1_pixe_mask5",
    "ContextMgmt_param_data_l3_rcr2_pixe_mask1",
    "ContextMgmt_param_data_l3_rcr2_pixe_mask2",
    "ContextMgmt_param_data_l3_rcr2_pixe_mask3",
    "ContextMgmt_param_data_l3_rcr2_pixe_mask4",
    "ContextMgmt_param_data_l3_rcr2_pixe_mask5",
    "ContextMgmt_param_data_l3_rcr3_pixe_mask1",
    "ContextMgmt_param_data_l3_rcr3_pixe_mask2",
    "ContextMgmt_param_data_l3_rcr3_pixe_mask3",
    "ContextMgmt_param_data_l3_rcr3_pixe_mask4",
    "ContextMgmt_param_data_l3_rcr3_pixe_mask5",
    "ContextMgmt_param_data_l3_rcr4_pixe_mask1",
    "ContextMgmt_param_data_l3_rcr4_pixe_mask2",
    "ContextMgmt_param_data_l3_rcr4_pixe_mask3",
    "ContextMgmt_param_data_l3_rcr4_pixe_mask4",
    "ContextMgmt_param_data_l3_rcr4_pixe_mask5",
    "ContextMgmt_param_data_l3_rcr5_pixe_mask1",
    "ContextMgmt_param_data_l3_rcr5_pixe_mask2",
    "ContextMgmt_param_data_l3_rcr5_pixe_mask3",
    "ContextMgmt_param_data_l3_rcr5_pixe_mask4",
    "ContextMgmt_param_data_l3_rcr5_pixe_mask5",
    "ContextMgmt_param_data_l3_rcr6_pixe_mask1",
    "ContextMgmt_param_data_l3_rcr6_pixe_mask2",
    "ContextMgmt_param_data_l3_rcr6_pixe_mask3",
    "ContextMgmt_param_data_l3_rcr6_pixe_mask4",
    "ContextMgmt_param_data_l3_rcr6_pixe_mask5",
    "ContextMgmt_param_data_l3_rcr7_pixe_mask1",
    "ContextMgmt_param_data_l3_rcr7_pixe_mask2",
    "ContextMgmt_param_data_l3_rcr7_pixe_mask3",
    "ContextMgmt_param_data_l3_rcr7_pixe_mask4",
    "ContextMgmt_param_data_l3_rcr7_pixe_mask5",
    "ContextMgmt_param_data_l3_rcr8_pixe_mask1",
    "ContextMgmt_param_data_l3_rcr8_pixe_mask2",
    "ContextMgmt_param_data_l3_rcr8_pixe_mask3",
    "ContextMgmt_param_data_l3_rcr8_pixe_mask4",
    "ContextMgmt_param_data_l3_rcr8_pixe_mask5",
    "ContextMgmt_param_data_enable_bckg_dete_formatting",
    "ContextMgmt_param_data_enable_cfl_dete_formatting",
    "ContextMgmt_param_imaging_dete_mask", "ContextMgmt_param_imaging_trim_N",
    "ContextMgmt_param_imaging_trim_F",
    "ContextMgmt_param_imaging_bckg_determination",
    "ContextMgmt_param_spectro_dete_mask",
    "ContextMgmt_param_spectro_pixe_mask",
    "ContextMgmt_param_spectro_bckg_determination",
    "ContextMgmt_param_xray01_registers", "ContextMgmt_param_xray02_registers",
    "ContextMgmt_param_xray03_registers", "ContextMgmt_param_xray04_registers",
    "ContextMgmt_param_xray05_registers", "ContextMgmt_param_xray06_registers",
    "ContextMgmt_param_xray07_registers", "ContextMgmt_param_xray08_registers",
    "ContextMgmt_param_xray09_registers", "ContextMgmt_param_xray10_registers",
    "ContextMgmt_param_xray11_registers", "ContextMgmt_param_xray12_registers",
    "ContextMgmt_param_xray13_registers", "ContextMgmt_param_xray14_registers",
    "ContextMgmt_param_xray15_registers", "ContextMgmt_param_xray16_registers",
    "ContextMgmt_param_xray17_registers", "ContextMgmt_param_xray18_registers",
    "ContextMgmt_param_xray19_registers", "ContextMgmt_param_xray20_registers",
    "ContextMgmt_param_xray21_registers", "ContextMgmt_param_xray22_registers",
    "ContextMgmt_param_xray23_registers", "ContextMgmt_param_xray24_registers",
    "ContextMgmt_param_xray25_registers", "ContextMgmt_param_xray26_registers",
    "ContextMgmt_param_xray27_registers", "ContextMgmt_param_xray28_registers",
    "ContextMgmt_param_xray29_registers", "ContextMgmt_param_xray30_registers",
    "ContextMgmt_param_xray31_registers", "ContextMgmt_param_xray32_registers",
    "ContextMgmt_param_hk_period_sid2", "ContextMgmt_param_hk_period_sid4",
    "ContextMgmt_param_enabled_science_data_transfer",
    "ContextMgmt_param_elut_lut", "ContextMgmt_param_tlut1_lut",
    "ContextMgmt_param_tlut2_lut", "ContextMgmt_param_tlut_dete_quarter_mask",
    "ContextMgmt_param_tlut_number_of_temperatures_for_average",
    "ContextMgmt_param_compression_l1l2_counts",
    "ContextMgmt_param_compression_l1l2l3_triggers",
    "ContextMgmt_param_compression_l3_counts",
    "ContextMgmt_param_compression_spectro_counts",
    "ContextMgmt_param_tmmgmt_publishing_interval",
    "ContextMgmt_param_tmmgmt_corridor_t1",
    "ContextMgmt_param_tmmgmt_corridor_t2",
    "ContextMgmt_param_tmmgmt_corridor_m1",
    "ContextMgmt_param_tmmgmt_corridor_m2",
    "ContextMgmt_param_aspect_halves_power",
    "ContextMgmt_param_att_openned_motor",
    "ContextMgmt_param_calib_compression_schema",
    "ContextMgmt_param_calib_formatting_enabled",
    "ContextMgmt_param_calib_pixel_mask",
    "ContextMgmt_param_config_adc_enable_mask",
    "ContextMgmt_param_config_adc_mode_mask",
    "ContextMgmt_param_config_enabled_edac",
    "ContextMgmt_param_config_scrub_cache",
    "ContextMgmt_param_config_scrub_sdram",
    "ContextMgmt_param_config_spw_state", "ContextMgmt_param_detector_mask_l1",
    "ContextMgmt_param_detector_mask_l2", "ContextMgmt_param_detector_mask_l3",
    "ContextMgmt_param_detector_mask_l4",
    "ContextMgmt_param_edac_scrub_algo_cache_threshold_high",
    "ContextMgmt_param_edac_scrub_algo_cache_threshold_nom",
    "ContextMgmt_param_edac_scrub_algo_sdram_threshold_high",
    "ContextMgmt_param_edac_scrub_algo_sdram_threshold_nom",
    "ContextMgmt_param_edac_seu_report_period_s",
    "ContextMgmt_param_fdir_irq_counter_max_dataflash",
    "ContextMgmt_param_fdir_irq_counter_max_detector",
    "ContextMgmt_param_fdir_irq_counter_max_detector_ql",
    "ContextMgmt_param_fdir_irq_counter_max_spw",
    "ContextMgmt_param_flare_list_last_report_scet",
    "ContextMgmt_param_hk_tm_sid2_reporting_enabled",
    "ContextMgmt_param_hk_tm_sid4_reporting_enabled",
    "ContextMgmt_param_hv_reset_delay_from_flare", "ContextMgmt_param_lv_state",
    "ContextMgmt_param_mem_load_enabled", "ContextMgmt_param_fdir_sw_psut_min",
    "ContextMgmt_param_ql_flaredet_dete_mask",
    "ContextMgmt_param_ql_spectrum_number_of_wait_iterations",
    "ContextMgmt_param_rcr_b0",
    "ContextMgmt_param_spw_time_code_reception_timeout_ms",
    "ContextMgmt_param_fdir_sw_psut_max", "ContextMgmt_param_flare_sel_period",
    "ContextMgmt_param_flare_sel_latency",
    "ContextMgmt_param_flare_sel_enabled", "ContextMgmt_param_flare_sel_start",
    "ContextMgmt_param_flare_sel_stop",
    "ContextMgmt_param_fs_rewrite_files_after_n_seus",
    "ContextMgmt_params_att_global_disable_flag",
    "ContextMgmt_params_asic_latency_delay"
]
sizes = [
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
    8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 4, 32, 8, 8, 8,
    12, 32, 16, 16, 16, 16, 16, 32, 8, 16, 16, 1, 1, 8, 8, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 3, 8, 8, 1, 1, 16, 16, 32, 1, 16, 32, 16, 8, 30, 30, 30, 30, 30, 30,
    30, 30, 32, 1, 16, 16, 1, 1, 32, 32, 32, 32, 32, 32, 32, 32, 8, 7, 7, 1,
    32, 1, 32, 1, 8, 7, 7, 32, 12, 12, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32,
    32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 16, 16, 32, 32, 32, 32, 32,
    32, 32, 32, 32, 1, 8, 8, 32, 32, 16, 32, 32, 8, 8, 16, 8, 8, 8, 8, 3, 3,
    32, 32, 8, 8, 32, 4, 4, 32, 32, 8, 1, 7, 7, 32, 32, 12, 1, 7, 1, 16, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 24, 13, 13, 13, 13, 13, 13, 13, 13, 32, 32, 32, 32, 16, 16, 32,
    32, 32, 3, 32, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 1, 1,
    32, 8, 8, 1, 32, 12, 1, 282, 282, 282, 282, 282, 282, 282, 282, 282, 282,
    282, 282, 282, 282, 282, 282, 282, 282, 282, 282, 282, 282, 282, 282, 282,
    282, 282, 282, 282, 282, 282, 282, 16, 16, 32, 16, 16, 16, 4, 8, 7, 7, 7,
    7, 32, 32, 32, 32, 32, 16, 2, 7, 1, 16, 16, 16, 4, 2, 2, 2, 32, 32, 32, 32,
    32, 32, 32, 32, 16, 32, 32, 32, 32, 32, 1, 1, 16, 1, 1, 12, 32, 7, 32, 32,
    12, 8, 8, 1, 32, 32, 8, 8, 8
]
reg = {  #register bitsize
    'REG01': 2,
    'REG02': 3,
    'REG03_TH_1': 6,  #6x32=192
    'REG03_TH_2': 6,
    'REG03_TH_3': 6,
    'REG03_TH_4': 6,
    'REG03_TH_5': 6,
    'REG03_TH_6': 6,
    'REG03_TH_7': 6,
    'REG03_TH_8': 6,
    'REG03_TH_9': 6,
    'REG03_TH_10': 6,
    'REG03_TH_11': 6,
    'REG03_TH_12': 6,
    'REG03_TH_13': 6,
    'REG03_TH_14': 6,
    'REG03_TH_15': 6,
    'REG03_TH_16': 6,
    'REG03_TH_17': 6,
    'REG03_TH_18': 6,
    'REG03_TH_19': 6,
    'REG03_TH_20': 6,
    'REG03_TH_21': 6,
    'REG03_TH_22': 6,
    'REG03_TH_23': 6,
    'REG03_TH_24': 6,
    'REG03_TH_25': 6,
    'REG03_TH_26': 6,
    'REG03_TH_27': 6,
    'REG03_TH_28': 6,
    'REG03_TH_29': 6,
    'REG03_TH_30': 6,
    'REG03_TH_31': 6,
    'REG03_TH_32': 6,
    'REG04': 32,
    'REG05': 4,
    'REG06': 2,
    'REG07': 5,
    'REG08': 2,
    'REG09': 2,
    'REG10': 3,
    'REG11': 3,
    'REG12': 32
}

s = [(n, s) for n, s in zip(names, sizes)]
pprint.pprint(s)

pprint.pprint([(k, v) for k, v in reg.items()])

s2 = [n for n in names if 'xray' in n]
pprint.pprint(s2)
