//taken from  the source code
// This is an open source non-commercial project. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++, C#, and Java: http://www.viva64.com

#include "TcTm/TCData.h"
#include "TcTm/TM/TMForm.h"
#include "TcTm/TM/TM_22.h"
#include "TcTm/TMBuffer.h"
#include "SWStatus/ParamMgmt.h"
#include "HWControl/XRayADCsCtrl.h"
#include "MemoryMgmt/FilesystemAPI.h"
#include "utils.h"
#include "ContextMgmt.h"

#include "BSW/include/Common.h"

#define TRACE_TAG  "Context"

#if ! ENABLE_TRACE_CONTEXT
#undef TRACE
#define TRACE(...)
#endif

#define CONTEXT_DETE_REG01_SIZE    2
#define CONTEXT_DETE_REG02_SIZE    3
#define CONTEXT_DETE_REG03_SIZE    72
#define CONTEXT_DETE_REG04_SIZE    12
#define CONTEXT_DETE_REG05_SIZE    4
#define CONTEXT_DETE_REG06_SIZE    2
#define CONTEXT_DETE_REG07_SIZE    5
#define CONTEXT_DETE_REG08_SIZE    2
#define CONTEXT_DETE_REG09_SIZE    2
#define CONTEXT_DETE_REG10_SIZE    3
#define CONTEXT_DETE_REG11_SIZE    3
#define CONTEXT_DETE_REG12_SIZE    12

static const uint8_t context_register_bit_size[ASIC_NUMBER_OF_REGISTERS] =
{
	CONTEXT_DETE_REG01_SIZE, CONTEXT_DETE_REG02_SIZE, CONTEXT_DETE_REG03_SIZE, CONTEXT_DETE_REG04_SIZE,
	CONTEXT_DETE_REG05_SIZE, CONTEXT_DETE_REG06_SIZE, CONTEXT_DETE_REG07_SIZE, CONTEXT_DETE_REG08_SIZE,
	CONTEXT_DETE_REG09_SIZE, CONTEXT_DETE_REG10_SIZE, CONTEXT_DETE_REG11_SIZE, CONTEXT_DETE_REG12_SIZE,
};

#define CONTEXT_DETE_REG01_OFFSET  0
#define CONTEXT_DETE_REG02_OFFSET  (CONTEXT_DETE_REG01_SIZE+CONTEXT_DETE_REG01_OFFSET)
#define CONTEXT_DETE_REG03_OFFSET  (CONTEXT_DETE_REG02_SIZE+CONTEXT_DETE_REG02_OFFSET)
#define CONTEXT_DETE_REG04_OFFSET  (CONTEXT_DETE_REG03_SIZE+CONTEXT_DETE_REG03_OFFSET)
#define CONTEXT_DETE_REG05_OFFSET  (CONTEXT_DETE_REG04_SIZE+CONTEXT_DETE_REG04_OFFSET)
#define CONTEXT_DETE_REG06_OFFSET  (CONTEXT_DETE_REG05_SIZE+CONTEXT_DETE_REG05_OFFSET)
#define CONTEXT_DETE_REG07_OFFSET  (CONTEXT_DETE_REG06_SIZE+CONTEXT_DETE_REG06_OFFSET)
#define CONTEXT_DETE_REG08_OFFSET  (CONTEXT_DETE_REG07_SIZE+CONTEXT_DETE_REG07_OFFSET)
#define CONTEXT_DETE_REG09_OFFSET  (CONTEXT_DETE_REG08_SIZE+CONTEXT_DETE_REG08_OFFSET)
#define CONTEXT_DETE_REG10_OFFSET  (CONTEXT_DETE_REG09_SIZE+CONTEXT_DETE_REG09_OFFSET)
#define CONTEXT_DETE_REG11_OFFSET  (CONTEXT_DETE_REG10_SIZE+CONTEXT_DETE_REG10_OFFSET)
#define CONTEXT_DETE_REG12_OFFSET  (CONTEXT_DETE_REG11_SIZE+CONTEXT_DETE_REG11_OFFSET)

static const uint8_t context_register_bit_offset[ASIC_NUMBER_OF_REGISTERS] =
{
	CONTEXT_DETE_REG01_OFFSET, CONTEXT_DETE_REG02_OFFSET, CONTEXT_DETE_REG03_OFFSET, CONTEXT_DETE_REG04_OFFSET,
	CONTEXT_DETE_REG05_OFFSET, CONTEXT_DETE_REG06_OFFSET, CONTEXT_DETE_REG07_OFFSET, CONTEXT_DETE_REG08_OFFSET,
	CONTEXT_DETE_REG09_OFFSET, CONTEXT_DETE_REG10_OFFSET, CONTEXT_DETE_REG11_OFFSET, CONTEXT_DETE_REG12_OFFSET,
};

//THE FOLLOWING LINES ARE MACHINE-GENERATED BY Parameter_table_context_macro_v2.xlsm
//MANUAL CHANGES MAY BE OVERWRITTEN IN THE FUTURE
typedef enum ContextMgmt_param_id_enum
{
	ContextMgmt_param_fdir_sw_1v5c_min,
	ContextMgmt_param_fdir_sw_1v5c_max,
	ContextMgmt_param_fdir_hw_1v5c,
	ContextMgmt_param_fdir_sw_2v5c_min,
	ContextMgmt_param_fdir_sw_2v5c_max,
	ContextMgmt_param_fdir_hw_2v5c,
	ContextMgmt_param_fdir_sw_3v3c_min,
	ContextMgmt_param_fdir_sw_3v3c_max,
	ContextMgmt_param_fdir_hw_3v3c,
	ContextMgmt_param_fdir_sw_spw0c_min,
	ContextMgmt_param_fdir_sw_spw0c_max,
	ContextMgmt_param_fdir_sw_spw1c_min,
	ContextMgmt_param_fdir_sw_spw1c_max,
	ContextMgmt_param_fdir_sw_spw2c_min,
	ContextMgmt_param_fdir_sw_spw2c_max,
	ContextMgmt_param_fdir_hw_spwc,
	ContextMgmt_param_fdir_sw_det0c_min,
	ContextMgmt_param_fdir_sw_det0c_max,
	ContextMgmt_param_fdir_sw_det1c_min,
	ContextMgmt_param_fdir_sw_det1c_max,
	ContextMgmt_param_fdir_sw_det2c_min,
	ContextMgmt_param_fdir_sw_det2c_max,
	ContextMgmt_param_fdir_sw_det3c_min,
	ContextMgmt_param_fdir_sw_det3c_max,
	ContextMgmt_param_fdir_sw_det4c_min,
	ContextMgmt_param_fdir_sw_det4c_max,
	ContextMgmt_param_fdir_hw_detc,
	ContextMgmt_param_fdir_sw_att0c_min,
	ContextMgmt_param_fdir_sw_att0c_max,
	ContextMgmt_param_fdir_sw_att1c_min,
	ContextMgmt_param_fdir_sw_att1c_max,
	ContextMgmt_param_fdir_sw_att2c_min,
	ContextMgmt_param_fdir_sw_att2c_max,
	ContextMgmt_param_fdir_hw_attc,
	ContextMgmt_param_fdir_sw_attv_min,
	ContextMgmt_param_fdir_sw_attv_max,
	ContextMgmt_param_fdir_hw_attv,
	ContextMgmt_param_fdir_sw_hw01_min,
	ContextMgmt_param_fdir_sw_hw01_max,
	ContextMgmt_param_fdir_hw_hw01,
	ContextMgmt_param_fdir_sw_hw02_min,
	ContextMgmt_param_fdir_sw_hw02_max,
	ContextMgmt_param_fdir_hw_hw02,
	ContextMgmt_param_fdir_sw_2v9v_min,
	ContextMgmt_param_fdir_sw_2v9v_max,
	ContextMgmt_param_fdir_sw_2v5v_min,
	ContextMgmt_param_fdir_sw_2v5v_max,
	ContextMgmt_param_fdir_sw_1v5v_min,
	ContextMgmt_param_fdir_sw_1v5v_max,
	ContextMgmt_param_fdir_sw_spw0v_min,
	ContextMgmt_param_fdir_sw_spw0v_max,
	ContextMgmt_param_fdir_sw_spw1v_min,
	ContextMgmt_param_fdir_sw_spw1v_max,
	ContextMgmt_param_fdir_sw_asp_vsensa_min,
	ContextMgmt_param_fdir_sw_asp_vsensa_max,
	ContextMgmt_param_fdir_sw_asp_vsensb_min,
	ContextMgmt_param_fdir_sw_asp_vsensb_max,
	ContextMgmt_param_fdir_sw_asp_refa_min,
	ContextMgmt_param_fdir_sw_asp_refa_max,
	ContextMgmt_param_fdir_sw_asp_refb_min,
	ContextMgmt_param_fdir_sw_asp_refb_max,
	ContextMgmt_param_fdir_sw_asp_photoA0_min,
	ContextMgmt_param_fdir_sw_asp_photoA0_max,
	ContextMgmt_param_fdir_sw_asp_photoA1_min,
	ContextMgmt_param_fdir_sw_asp_photoA1_max,
	ContextMgmt_param_fdir_sw_asp_photoB0_min,
	ContextMgmt_param_fdir_sw_asp_photoB0_max,
	ContextMgmt_param_fdir_sw_asp_photoB1_min,
	ContextMgmt_param_fdir_sw_asp_photoB1_max,
	ContextMgmt_param_fdir_sw_fpgat_min,
	ContextMgmt_param_fdir_sw_fpgat_max,
	ContextMgmt_param_fdir_sw_pcbt_min,
	ContextMgmt_param_fdir_sw_pcbt_max,
	ContextMgmt_param_fdir_sw_tim01t_min,
	ContextMgmt_param_fdir_sw_tim01t_max,
	ContextMgmt_param_fdir_sw_tim02t_min,
	ContextMgmt_param_fdir_sw_tim02t_max,
	ContextMgmt_param_fdir_sw_tim03t_min,
	ContextMgmt_param_fdir_sw_tim03t_max,
	ContextMgmt_param_fdir_sw_tim04t_min,
	ContextMgmt_param_fdir_sw_tim04t_max,
	ContextMgmt_param_fdir_sw_tim05t_min,
	ContextMgmt_param_fdir_sw_tim05t_max,
	ContextMgmt_param_fdir_sw_tim06t_min,
	ContextMgmt_param_fdir_sw_tim06t_max,
	ContextMgmt_param_fdir_sw_tim07t_min,
	ContextMgmt_param_fdir_sw_tim07t_max,
	ContextMgmt_param_fdir_sw_tim08t_min,
	ContextMgmt_param_fdir_sw_tim08t_max,
	ContextMgmt_param_fdir_sw_det01t_min,
	ContextMgmt_param_fdir_sw_det01t_max,
	ContextMgmt_param_fdir_sw_det02t_min,
	ContextMgmt_param_fdir_sw_det02t_max,
	ContextMgmt_param_fdir_sw_det03t_min,
	ContextMgmt_param_fdir_sw_det03t_max,
	ContextMgmt_param_fdir_sw_det04t_min,
	ContextMgmt_param_fdir_sw_det04t_max,
	ContextMgmt_param_fdir_sw_attt_min,
	ContextMgmt_param_fdir_sw_attt_max,
	ContextMgmt_param_fdir_meas_trig_psut,
	ContextMgmt_param_fdir_meas_trig_pcbt,
	ContextMgmt_param_fdir_meas_trig_fpgat,
	ContextMgmt_param_fdir_meas_trig_3v3c,
	ContextMgmt_param_fdir_meas_trig_2v5c,
	ContextMgmt_param_fdir_meas_trig_1v5c,
	ContextMgmt_param_fdir_meas_trig_spwc,
	ContextMgmt_param_fdir_meas_trig_spw0v,
	ContextMgmt_param_fdir_meas_trig_spw1v,
	ContextMgmt_param_fdir_meas_trig_1v5v,
	ContextMgmt_param_fdir_meas_trig_2v5v,
	ContextMgmt_param_fdir_meas_trig_2v9v,
	ContextMgmt_param_fdir_meas_trig_attv,
	ContextMgmt_param_fdir_meas_trig_attc,
	ContextMgmt_param_fdir_meas_trig_attt,
	ContextMgmt_param_fdir_meas_trig_hv01,
	ContextMgmt_param_fdir_meas_trig_hv02,
	ContextMgmt_param_fdir_meas_trig_detc,
	ContextMgmt_param_fdir_meas_trig_detq1t,
	ContextMgmt_param_fdir_meas_trig_detq2t,
	ContextMgmt_param_fdir_meas_trig_detq3t,
	ContextMgmt_param_fdir_meas_trig_detq4t,
	ContextMgmt_param_fdir_meas_trig_asp_refa,
	ContextMgmt_param_fdir_meas_trig_asp_refb,
	ContextMgmt_param_fdir_meas_trig_tim01t,
	ContextMgmt_param_fdir_meas_trig_tim02t,
	ContextMgmt_param_fdir_meas_trig_tim03t,
	ContextMgmt_param_fdir_meas_trig_tim04t,
	ContextMgmt_param_fdir_meas_trig_tim05t,
	ContextMgmt_param_fdir_meas_trig_tim06t,
	ContextMgmt_param_fdir_meas_trig_tim07t,
	ContextMgmt_param_fdir_meas_trig_tim08t,
	ContextMgmt_param_fdir_meas_trig_asp_vsensa,
	ContextMgmt_param_fdir_meas_trig_asp_vsensb,
	ContextMgmt_param_fdir_meas_trig_asp_photoa0,
	ContextMgmt_param_fdir_meas_trig_asp_photoa1,
	ContextMgmt_param_fdir_meas_trig_asp_photob0,
	ContextMgmt_param_fdir_meas_trig_asp_photob1,
	ContextMgmt_param_fdir_seu_ignore_flag,
	ContextMgmt_param_fdir_enabled_dete_quarter,
	ContextMgmt_param_fdir_att_number_moves,
	ContextMgmt_param_fdir_att_N1,
	ContextMgmt_param_fdir_att_T1,
	ContextMgmt_param_fdir_att_N2,
	ContextMgmt_param_fdir_att_T2,
	ContextMgmt_param_fdir_asic_verif_disabled_dete_mask,
	ContextMgmt_param_fdir_asic_verif_period,
	ContextMgmt_param_fdir_hv01_depolarisation_period,
	ContextMgmt_param_fdir_hv02_depolarisation_period,
	ContextMgmt_param_fdir_hv01_depolarisation_duration,
	ContextMgmt_param_fdir_hv02_depolarisation_duration,
	ContextMgmt_param_fdir_enabled_function_mask,
	ContextMgmt_param_fdir_enabled_current_function_checks,
	ContextMgmt_param_fdir_enabled_voltage_function_checks,
	ContextMgmt_param_fdir_enabled_temperature_function_checks,
	ContextMgmt_param_config_hv01_line_enabled,
	ContextMgmt_param_config_hv02_line_enabled,
	ContextMgmt_param_config_hv01_value,
	ContextMgmt_param_config_hv02_value,
	ContextMgmt_param_config_spw_ocp_state,
	ContextMgmt_param_config_det_ocp_state,
	ContextMgmt_param_config_att_ocp_state,
	ContextMgmt_param_config_1v5_ocp_state,
	ContextMgmt_param_config_2v5_ocp_state,
	ContextMgmt_param_config_3v3_ocp_state,
	ContextMgmt_param_config_att_ovp_state,
	ContextMgmt_param_config_hv1_ovp_state,
	ContextMgmt_param_config_hv2_ovp_state,
	ContextMgmt_param_config_asp_fpga_readout_per_sum,
	ContextMgmt_param_config_att_max_pwm,
	ContextMgmt_param_config_att_nom_pwm,
	ContextMgmt_param_config_fsw_s20_reaction_state,
	ContextMgmt_param_config_fsw_enable_tm51,
	ContextMgmt_param_config_sdram_prescaler,
	ContextMgmt_param_config_rotb_prescaler,
	ContextMgmt_param_config_spw_transient_duration,
	ContextMgmt_param_calib_cyclic_state,
	ContextMgmt_param_calib_tq,
	ContextMgmt_param_calib_detemask,
	ContextMgmt_param_calib_ta,
	ContextMgmt_param_calib_formatting_subspectra_mask,
	ContextMgmt_param_calib_formatting_subspectrum_1,
	ContextMgmt_param_calib_formatting_subspectrum_2,
	ContextMgmt_param_calib_formatting_subspectrum_3,
	ContextMgmt_param_calib_formatting_subspectrum_4,
	ContextMgmt_param_calib_formatting_subspectrum_5,
	ContextMgmt_param_calib_formatting_subspectrum_6,
	ContextMgmt_param_calib_formatting_subspectrum_7,
	ContextMgmt_param_calib_formatting_subspectrum_8,
	ContextMgmt_param_calib_formatting_detemask,
	ContextMgmt_param_calib_formatting_bit_reduction_flag,
	ContextMgmt_param_calib_formatting_pixelmask,
	ContextMgmt_param_ql_nominal_period,
	ContextMgmt_param_qlbg_enabled,
	ContextMgmt_param_qlbg_enabled_tm,
	ContextMgmt_param_qlbg_default_value_range_1,
	ContextMgmt_param_qlbg_default_value_range_2,
	ContextMgmt_param_qlbg_default_value_range_3,
	ContextMgmt_param_qlbg_default_value_range_4,
	ContextMgmt_param_qlbg_default_value_range_5,
	ContextMgmt_param_qlbg_default_value_range_6,
	ContextMgmt_param_qlbg_default_value_range_7,
	ContextMgmt_param_qlbg_default_value_range_8,
	ContextMgmt_param_qlbg_ql_integration_per_datum,
	ContextMgmt_param_qlbg_compression_scheme_counts,
	ContextMgmt_param_qlbg_compression_scheme_triggers,
	ContextMgmt_param_qlbg_energy_bin_edge_mask_upper_bit,
	ContextMgmt_param_qlbg_energy_bin_edge_mask_lower_bits,
	ContextMgmt_param_qllc_energy_bin_edge_mask_upper_bit,
	ContextMgmt_param_qllc_energy_bin_edge_mask_lower_bits,
	ContextMgmt_param_qllc_enable_tm,
	ContextMgmt_param_qllc_ql_integration_per_datum,
	ContextMgmt_param_qllc_compression_scheme_counts,
	ContextMgmt_param_qllc_compression_scheme_triggers,
	ContextMgmt_param_qllc_detemask,
	ContextMgmt_param_qllc_pixemask,
	ContextMgmt_param_qlfdet_pixemask,
	ContextMgmt_param_qlfdet_thermal_energy_mask,
	ContextMgmt_param_qlfdet_nonthermal_energy_mask,
	ContextMgmt_param_qlfdet_kb,
	ContextMgmt_param_qlfdet_thermal_factor_rcr1,
	ContextMgmt_param_qlfdet_thermal_factor_rcr2,
	ContextMgmt_param_qlfdet_thermal_factor_rcr3,
	ContextMgmt_param_qlfdet_thermal_factor_rcr4,
	ContextMgmt_param_qlfdet_thermal_factor_rcr5,
	ContextMgmt_param_qlfdet_thermal_factor_rcr6,
	ContextMgmt_param_qlfdet_thermal_factor_rcr7,
	ContextMgmt_param_qlfdet_thermal_factor_rcr8,
	ContextMgmt_param_qlfdet_nonthermal_factor_rcr1,
	ContextMgmt_param_qlfdet_nonthermal_factor_rcr2,
	ContextMgmt_param_qlfdet_nonthermal_factor_rcr3,
	ContextMgmt_param_qlfdet_nonthermal_factor_rcr4,
	ContextMgmt_param_qlfdet_nonthermal_factor_rcr5,
	ContextMgmt_param_qlfdet_nonthermal_factor_rcr6,
	ContextMgmt_param_qlfdet_nonthermal_factor_rcr7,
	ContextMgmt_param_qlfdet_nonthermal_factor_rcr8,
	ContextMgmt_param_qlfdet_k,
	ContextMgmt_param_qlfdet_kp,
	ContextMgmt_param_qlfdet_kpp,
	ContextMgmt_param_qlfdet_timescale_short,
	ContextMgmt_param_qlfdet_timescale_long,
	ContextMgmt_param_qlfdet_init_thermal_cbc,
	ContextMgmt_param_qlfdet_init_nonthermal_cbc,
	ContextMgmt_param_qlfdet_cfmin,
	ContextMgmt_param_qlfdet_threshold_thermal_B1,
	ContextMgmt_param_qlfdet_threshold_thermal_C1,
	ContextMgmt_param_qlfdet_threshold_thermal_M1,
	ContextMgmt_param_qlfdet_threshold_thermal_X1,
	ContextMgmt_param_qlfdet_threshold_nonthermal_weak,
	ContextMgmt_param_qlfdet_threshold_nonthermal_significant,
	ContextMgmt_param_qlfdetfloc_enable_tm,
	ContextMgmt_param_qlfdet_ql_integration_per_datum,
	ContextMgmt_param_qlffloc_ql_integration_per_datum,
	ContextMgmt_param_qlfloc_dete_mask,
	ContextMgmt_param_qlfloc_energy_mask,
	ContextMgmt_param_qlfloc_sky_table_id,
	ContextMgmt_param_qlfloc_L1,
	ContextMgmt_param_qlfloc_L2,
	ContextMgmt_param_qlfloc_k,
	ContextMgmt_param_qlfloc_kp,
	ContextMgmt_param_qlfloc_kpp,
	ContextMgmt_param_qlfloc_kppp,
	ContextMgmt_param_qlfloc_k0,
	ContextMgmt_param_qlfloc_k1,
	ContextMgmt_param_qlfloc_k2,
	ContextMgmt_param_qlfloc_dx,
	ContextMgmt_param_qlfloc_dy,
	ContextMgmt_param_qldmon_active_detector_mask,
	ContextMgmt_param_qldmon_energy_mask,
	ContextMgmt_param_qldmon_ql_integration_per_datum,
	ContextMgmt_param_qldmon_kbad,
	ContextMgmt_param_qldmon_rbad,
	ContextMgmt_param_qldmon_nbad,
	ContextMgmt_param_qldmon_nrep,
	ContextMgmt_param_qlsp_detemask,
	ContextMgmt_param_qlsp_pixemask,
	ContextMgmt_param_qlsp_ql_integrations_per_datum,
	ContextMgmt_param_qlsp_enable_tm,
	ContextMgmt_param_qlsp_compression_scheme_counts,
	ContextMgmt_param_qlsp_compression_scheme_triggers,
	ContextMgmt_param_qlvar_detemask,
	ContextMgmt_param_qlvar_enemask,
	ContextMgmt_param_qlvar_pixemask,
	ContextMgmt_param_qlvar_enable_tm,
	ContextMgmt_param_qlvar_compression_scheme_counts,
	ContextMgmt_param_qlrcr_enabled,
	ContextMgmt_param_qlrcr_group_mask,
	ContextMgmt_param_qlrcr_pixelmask_rcr0,
	ContextMgmt_param_qlrcr_pixelmask_rcr1,
	ContextMgmt_param_qlrcr_pixelmask_rcr2_north,
	ContextMgmt_param_qlrcr_pixelmask_rcr2_south,
	ContextMgmt_param_qlrcr_pixelmask_rcr3_north_1,
	ContextMgmt_param_qlrcr_pixelmask_rcr3_north_2,
	ContextMgmt_param_qlrcr_pixelmask_rcr3_south_1,
	ContextMgmt_param_qlrcr_pixelmask_rcr3_south_2,
	ContextMgmt_param_qlrcr_pixelmask_rcr4_north_1,
	ContextMgmt_param_qlrcr_pixelmask_rcr4_north_2,
	ContextMgmt_param_qlrcr_pixelmask_rcr4_north_3,
	ContextMgmt_param_qlrcr_pixelmask_rcr4_north_4,
	ContextMgmt_param_qlrcr_pixelmask_rcr4_south_1,
	ContextMgmt_param_qlrcr_pixelmask_rcr4_south_2,
	ContextMgmt_param_qlrcr_pixelmask_rcr4_south_3,
	ContextMgmt_param_qlrcr_pixelmask_rcr4_south_4,
	ContextMgmt_param_qlrcr_pixelmask_rcr5,
	ContextMgmt_param_qlrcr_pixelmask_rcr6_1,
	ContextMgmt_param_qlrcr_pixelmask_rcr6_2,
	ContextMgmt_param_qlrcr_pixelmask_rcr7_1,
	ContextMgmt_param_qlrcr_pixelmask_rcr7_2,
	ContextMgmt_param_qlrcr_pixelmask_rcr7_3,
	ContextMgmt_param_qlrcr_pixelmask_rcr7_4,
	ContextMgmt_param_qlrcr_regime2state_lut,
	ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr0,
	ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr1,
	ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr2,
	ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr3,
	ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr4,
	ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr5,
	ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr6,
	ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr7,
	ContextMgmt_param_qlrcr_L0,
	ContextMgmt_param_qlrcr_L1,
	ContextMgmt_param_qlrcr_L2,
	ContextMgmt_param_qlrcr_L3,
	ContextMgmt_param_accum_max_duration,
	ContextMgmt_param_accum_min_duration,
	ContextMgmt_param_accum_max_counts,
	ContextMgmt_param_accum_sum_e_mask,
	ContextMgmt_param_accum_sum_d_mask,
	ContextMgmt_param_data_level,
	ContextMgmt_param_data_l0_dete_mask,
	ContextMgmt_param_data_l0_pixe_mask,
	ContextMgmt_param_data_l1_rcr1_pixe_mask,
	ContextMgmt_param_data_l1_rcr2_pixe_mask,
	ContextMgmt_param_data_l1_rcr3_pixe_mask,
	ContextMgmt_param_data_l1_rcr4_pixe_mask,
	ContextMgmt_param_data_l1_rcr5_pixe_mask,
	ContextMgmt_param_data_l1_rcr6_pixe_mask,
	ContextMgmt_param_data_l1_rcr7_pixe_mask,
	ContextMgmt_param_data_l1_rcr8_pixe_mask,
	ContextMgmt_param_data_l2_rcr1_pixe_mask1,
	ContextMgmt_param_data_l2_rcr1_pixe_mask2,
	ContextMgmt_param_data_l2_rcr1_pixe_mask3,
	ContextMgmt_param_data_l2_rcr1_pixe_mask4,
	ContextMgmt_param_data_l2_rcr1_pixe_mask5,
	ContextMgmt_param_data_l2_rcr2_pixe_mask1,
	ContextMgmt_param_data_l2_rcr2_pixe_mask2,
	ContextMgmt_param_data_l2_rcr2_pixe_mask3,
	ContextMgmt_param_data_l2_rcr2_pixe_mask4,
	ContextMgmt_param_data_l2_rcr2_pixe_mask5,
	ContextMgmt_param_data_l2_rcr3_pixe_mask1,
	ContextMgmt_param_data_l2_rcr3_pixe_mask2,
	ContextMgmt_param_data_l2_rcr3_pixe_mask3,
	ContextMgmt_param_data_l2_rcr3_pixe_mask4,
	ContextMgmt_param_data_l2_rcr3_pixe_mask5,
	ContextMgmt_param_data_l2_rcr4_pixe_mask1,
	ContextMgmt_param_data_l2_rcr4_pixe_mask2,
	ContextMgmt_param_data_l2_rcr4_pixe_mask3,
	ContextMgmt_param_data_l2_rcr4_pixe_mask4,
	ContextMgmt_param_data_l2_rcr4_pixe_mask5,
	ContextMgmt_param_data_l2_rcr5_pixe_mask1,
	ContextMgmt_param_data_l2_rcr5_pixe_mask2,
	ContextMgmt_param_data_l2_rcr5_pixe_mask3,
	ContextMgmt_param_data_l2_rcr5_pixe_mask4,
	ContextMgmt_param_data_l2_rcr5_pixe_mask5,
	ContextMgmt_param_data_l2_rcr6_pixe_mask1,
	ContextMgmt_param_data_l2_rcr6_pixe_mask2,
	ContextMgmt_param_data_l2_rcr6_pixe_mask3,
	ContextMgmt_param_data_l2_rcr6_pixe_mask4,
	ContextMgmt_param_data_l2_rcr6_pixe_mask5,
	ContextMgmt_param_data_l2_rcr7_pixe_mask1,
	ContextMgmt_param_data_l2_rcr7_pixe_mask2,
	ContextMgmt_param_data_l2_rcr7_pixe_mask3,
	ContextMgmt_param_data_l2_rcr7_pixe_mask4,
	ContextMgmt_param_data_l2_rcr7_pixe_mask5,
	ContextMgmt_param_data_l2_rcr8_pixe_mask1,
	ContextMgmt_param_data_l2_rcr8_pixe_mask2,
	ContextMgmt_param_data_l2_rcr8_pixe_mask3,
	ContextMgmt_param_data_l2_rcr8_pixe_mask4,
	ContextMgmt_param_data_l2_rcr8_pixe_mask5,
	ContextMgmt_param_data_l3_rcr1_pixe_mask1,
	ContextMgmt_param_data_l3_rcr1_pixe_mask2,
	ContextMgmt_param_data_l3_rcr1_pixe_mask3,
	ContextMgmt_param_data_l3_rcr1_pixe_mask4,
	ContextMgmt_param_data_l3_rcr1_pixe_mask5,
	ContextMgmt_param_data_l3_rcr2_pixe_mask1,
	ContextMgmt_param_data_l3_rcr2_pixe_mask2,
	ContextMgmt_param_data_l3_rcr2_pixe_mask3,
	ContextMgmt_param_data_l3_rcr2_pixe_mask4,
	ContextMgmt_param_data_l3_rcr2_pixe_mask5,
	ContextMgmt_param_data_l3_rcr3_pixe_mask1,
	ContextMgmt_param_data_l3_rcr3_pixe_mask2,
	ContextMgmt_param_data_l3_rcr3_pixe_mask3,
	ContextMgmt_param_data_l3_rcr3_pixe_mask4,
	ContextMgmt_param_data_l3_rcr3_pixe_mask5,
	ContextMgmt_param_data_l3_rcr4_pixe_mask1,
	ContextMgmt_param_data_l3_rcr4_pixe_mask2,
	ContextMgmt_param_data_l3_rcr4_pixe_mask3,
	ContextMgmt_param_data_l3_rcr4_pixe_mask4,
	ContextMgmt_param_data_l3_rcr4_pixe_mask5,
	ContextMgmt_param_data_l3_rcr5_pixe_mask1,
	ContextMgmt_param_data_l3_rcr5_pixe_mask2,
	ContextMgmt_param_data_l3_rcr5_pixe_mask3,
	ContextMgmt_param_data_l3_rcr5_pixe_mask4,
	ContextMgmt_param_data_l3_rcr5_pixe_mask5,
	ContextMgmt_param_data_l3_rcr6_pixe_mask1,
	ContextMgmt_param_data_l3_rcr6_pixe_mask2,
	ContextMgmt_param_data_l3_rcr6_pixe_mask3,
	ContextMgmt_param_data_l3_rcr6_pixe_mask4,
	ContextMgmt_param_data_l3_rcr6_pixe_mask5,
	ContextMgmt_param_data_l3_rcr7_pixe_mask1,
	ContextMgmt_param_data_l3_rcr7_pixe_mask2,
	ContextMgmt_param_data_l3_rcr7_pixe_mask3,
	ContextMgmt_param_data_l3_rcr7_pixe_mask4,
	ContextMgmt_param_data_l3_rcr7_pixe_mask5,
	ContextMgmt_param_data_l3_rcr8_pixe_mask1,
	ContextMgmt_param_data_l3_rcr8_pixe_mask2,
	ContextMgmt_param_data_l3_rcr8_pixe_mask3,
	ContextMgmt_param_data_l3_rcr8_pixe_mask4,
	ContextMgmt_param_data_l3_rcr8_pixe_mask5,
	ContextMgmt_param_data_enable_bckg_dete_formatting,
	ContextMgmt_param_data_enable_cfl_dete_formatting,
	ContextMgmt_param_imaging_dete_mask,
	ContextMgmt_param_imaging_trim_N,
	ContextMgmt_param_imaging_trim_F,
	ContextMgmt_param_imaging_bckg_determination,
	ContextMgmt_param_spectro_dete_mask,
	ContextMgmt_param_spectro_pixe_mask,
	ContextMgmt_param_spectro_bckg_determination,
	ContextMgmt_param_xray01_registers,
	ContextMgmt_param_xray02_registers,
	ContextMgmt_param_xray03_registers,
	ContextMgmt_param_xray04_registers,
	ContextMgmt_param_xray05_registers,
	ContextMgmt_param_xray06_registers,
	ContextMgmt_param_xray07_registers,
	ContextMgmt_param_xray08_registers,
	ContextMgmt_param_xray09_registers,
	ContextMgmt_param_xray10_registers,
	ContextMgmt_param_xray11_registers,
	ContextMgmt_param_xray12_registers,
	ContextMgmt_param_xray13_registers,
	ContextMgmt_param_xray14_registers,
	ContextMgmt_param_xray15_registers,
	ContextMgmt_param_xray16_registers,
	ContextMgmt_param_xray17_registers,
	ContextMgmt_param_xray18_registers,
	ContextMgmt_param_xray19_registers,
	ContextMgmt_param_xray20_registers,
	ContextMgmt_param_xray21_registers,
	ContextMgmt_param_xray22_registers,
	ContextMgmt_param_xray23_registers,
	ContextMgmt_param_xray24_registers,
	ContextMgmt_param_xray25_registers,
	ContextMgmt_param_xray26_registers,
	ContextMgmt_param_xray27_registers,
	ContextMgmt_param_xray28_registers,
	ContextMgmt_param_xray29_registers,
	ContextMgmt_param_xray30_registers,
	ContextMgmt_param_xray31_registers,
	ContextMgmt_param_xray32_registers,
	ContextMgmt_param_hk_period_sid2,
	ContextMgmt_param_hk_period_sid4,
	ContextMgmt_param_enabled_science_data_transfer,
	ContextMgmt_param_elut_lut,
	ContextMgmt_param_tlut1_lut,
	ContextMgmt_param_tlut2_lut,
	ContextMgmt_param_tlut_dete_quarter_mask,
	ContextMgmt_param_tlut_number_of_temperatures_for_average,
	ContextMgmt_param_compression_l1l2_counts,
	ContextMgmt_param_compression_l1l2l3_triggers,
	ContextMgmt_param_compression_l3_counts,
	ContextMgmt_param_compression_spectro_counts,
	ContextMgmt_param_tmmgmt_publishing_interval,
	ContextMgmt_param_tmmgmt_corridor_t1,
	ContextMgmt_param_tmmgmt_corridor_t2,
	ContextMgmt_param_tmmgmt_corridor_m1,
	ContextMgmt_param_tmmgmt_corridor_m2,
	ContextMgmt_param_aspect_halves_power,
	ContextMgmt_param_att_openned_motor,
	ContextMgmt_param_calib_compression_schema,
	ContextMgmt_param_calib_formatting_enabled,
	ContextMgmt_param_calib_pixel_mask,
	ContextMgmt_param_config_adc_enable_mask,
	ContextMgmt_param_config_adc_mode_mask,
	ContextMgmt_param_config_enabled_edac,
	ContextMgmt_param_config_scrub_cache,
	ContextMgmt_param_config_scrub_sdram,
	ContextMgmt_param_config_spw_state,
	ContextMgmt_param_detector_mask_l1,
	ContextMgmt_param_detector_mask_l2,
	ContextMgmt_param_detector_mask_l3,
	ContextMgmt_param_detector_mask_l4,
	ContextMgmt_param_edac_scrub_algo_cache_threshold_high,
	ContextMgmt_param_edac_scrub_algo_cache_threshold_nom,
	ContextMgmt_param_edac_scrub_algo_sdram_threshold_high,
	ContextMgmt_param_edac_scrub_algo_sdram_threshold_nom,
	ContextMgmt_param_edac_seu_report_period_s,
	ContextMgmt_param_fdir_irq_counter_max_dataflash,
	ContextMgmt_param_fdir_irq_counter_max_detector,
	ContextMgmt_param_fdir_irq_counter_max_detector_ql,
	ContextMgmt_param_fdir_irq_counter_max_spw,
	ContextMgmt_param_flare_list_last_report_scet,
	ContextMgmt_param_hk_tm_sid2_reporting_enabled,
	ContextMgmt_param_hk_tm_sid4_reporting_enabled,
	ContextMgmt_param_hv_reset_delay_from_flare,
	ContextMgmt_param_lv_state,
	ContextMgmt_param_mem_load_enabled,
	ContextMgmt_param_fdir_sw_psut_min,
	ContextMgmt_param_ql_flaredet_dete_mask,
	ContextMgmt_param_ql_spectrum_number_of_wait_iterations,
	ContextMgmt_param_rcr_b0,
	ContextMgmt_param_spw_time_code_reception_timeout_ms,
	ContextMgmt_param_fdir_sw_psut_max,
	ContextMgmt_param_flare_sel_period,
	ContextMgmt_param_flare_sel_latency,
	ContextMgmt_param_flare_sel_enabled,
	ContextMgmt_param_flare_sel_start,
	ContextMgmt_param_flare_sel_stop,
	ContextMgmt_param_fs_rewrite_files_after_n_seus,
	ContextMgmt_params_att_global_disable_flag,
	ContextMgmt_param_last
} __attribute__((__packed__)) ContextMgmt_param_id_e;

//THE FOLLOWING LINES ARE MACHINE-GENERATED BY Parameter_table_context_macro_v2.xlsm
//MANUAL CHANGES MAY BE OVERWRITTEN IN THE FUTURE
static const uint8_t ContextMgmt_paramBitSize[(uint16_t)ContextMgmt_param_last] =
{
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	8,
	4,
	4,
	32,
	8,
	8,
	8,
	12,
	32,
	16,
	16,
	16,
	16,
	16,
	32,
	8,
	16,
	16,
	1,
	1,
	8,
	8,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	3,
	8,
	8,
	1,
	1,
	16,
	16,
	32,
	1,
	16,
	32,
	16,
	8,
	30,
	30,
	30,
	30,
	30,
	30,
	30,
	30,
	32,
	1,
	16,
	16,
	1,
	1,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	8,
	7,
	7,
	1,
	32,
	1,
	32,
	1,
	8,
	7,
	7,
	32,
	12,
	12,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	16,
	16,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	1,
	8,
	8,
	32,
	32,
	16,
	32,
	32,
	8,
	8,
	16,
	8,
	8,
	8,
	8,
	3,
	3,
	32,
	32,
	8,
	8,
	32,
	4,
	4,
	32,
	32,
	8,
	1,
	7,
	7,
	32,
	32,
	12,
	1,
	7,
	1,
	16,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	24,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	13,
	32,
	32,
	32,
	32,
	16,
	16,
	32,
	32,
	32,
	3,
	32,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	12,
	1,
	1,
	32,
	8,
	8,
	1,
	32,
	12,
	1,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	122,
	16,
	16,
	32,
	16,
	16,
	16,
	4,
	8,
	7,
	7,
	7,
	7,
	32,
	32,
	32,
	32,
	32,
	16,
	2,
	7,
	1,
	16,
	16,
	16,
	4,
	2,
	2,
	2,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	32,
	16,
	32,
	32,
	32,
	32,
	32,
	1,
	1,
	16,
	1,
	1,
	12,
	32,
	7,
	32,
	32,
	12,
	8,
	8,
	1,
	32,
	32,
	8,
	8
};

typedef enum
{
	Value,
	Min,
	Max,
} __attribute__((__packed__)) ContextMgmt_param_part_e;

typedef struct
{
	ContextMgmt_param_id_e ctx;
	ParamMgmt_param_id_e param;
	ContextMgmt_param_part_e part;
} c2pmapping;


//THE FOLLOWING LINES ARE MACHINE-GENERATED BY Parameter_table_context_macro_v2.xlsm
//MANUAL CHANGES MAY BE OVERWRITTEN IN THE FUTURE
c2pmapping ContextMgmt_c2ptable[] =
{
	{ ContextMgmt_param_fdir_sw_1v5c_min, E_PARAM_ID_1V5_CURRENT, Min },
	{ ContextMgmt_param_fdir_sw_1v5c_max, E_PARAM_ID_1V5_CURRENT, Max },
	{ ContextMgmt_param_fdir_hw_1v5c, E_PARAM_ID_CONFIG_PSU_1V5_THRESHOLD, Value },
	{ ContextMgmt_param_fdir_sw_2v5c_min, E_PARAM_ID_2V5_CURRENT, Min },
	{ ContextMgmt_param_fdir_sw_2v5c_max, E_PARAM_ID_2V5_CURRENT, Max },
	{ ContextMgmt_param_fdir_hw_2v5c, E_PARAM_ID_CONFIG_PSU_2V5_THRESHOLD, Value },
	{ ContextMgmt_param_fdir_sw_3v3c_min, E_PARAM_ID_3V3_CURRENT, Min },
	{ ContextMgmt_param_fdir_sw_3v3c_max, E_PARAM_ID_3V3_CURRENT, Max },
	{ ContextMgmt_param_fdir_hw_3v3c, E_PARAM_ID_CONFIG_PSU_3V3_THRESHOLD, Value },
	{ ContextMgmt_param_fdir_sw_spw0c_min, E_PARAM_ID_SPW0L_CURRENT, Min },
	{ ContextMgmt_param_fdir_sw_spw0c_max, E_PARAM_ID_SPW0L_CURRENT, Max },
	{ ContextMgmt_param_fdir_sw_spw1c_min, E_PARAM_ID_SPW1L_CURRENT, Min },
	{ ContextMgmt_param_fdir_sw_spw1c_max, E_PARAM_ID_SPW1L_CURRENT, Max },
	{ ContextMgmt_param_fdir_sw_spw2c_min, E_PARAM_ID_SPW2L_CURRENT, Min },
	{ ContextMgmt_param_fdir_sw_spw2c_max, E_PARAM_ID_SPW2L_CURRENT, Max },
	{ ContextMgmt_param_fdir_hw_spwc, E_PARAM_ID_CONFIG_SPW_THRESHOLD_CURRENT, Value },
	{ ContextMgmt_param_fdir_sw_det0c_min, E_PARAM_ID_DET0Q_C, Min },
	{ ContextMgmt_param_fdir_sw_det0c_max, E_PARAM_ID_DET0Q_C, Max },
	{ ContextMgmt_param_fdir_sw_det1c_min, E_PARAM_ID_DET1Q_C, Min },
	{ ContextMgmt_param_fdir_sw_det1c_max, E_PARAM_ID_DET1Q_C, Max },
	{ ContextMgmt_param_fdir_sw_det2c_min, E_PARAM_ID_DET2Q_C, Min },
	{ ContextMgmt_param_fdir_sw_det2c_max, E_PARAM_ID_DET2Q_C, Max },
	{ ContextMgmt_param_fdir_sw_det3c_min, E_PARAM_ID_DET3Q_C, Min },
	{ ContextMgmt_param_fdir_sw_det3c_max, E_PARAM_ID_DET3Q_C, Max },
	{ ContextMgmt_param_fdir_sw_det4c_min, E_PARAM_ID_DET4Q_C, Min },
	{ ContextMgmt_param_fdir_sw_det4c_max, E_PARAM_ID_DET4Q_C, Max },
	{ ContextMgmt_param_fdir_hw_detc, E_PARAM_ID_CONFIG_DET_CURRENT_THRESHOLD, Value },
	{ ContextMgmt_param_fdir_sw_att0c_min, E_PARAM_ID_ATT0M_C, Min },
	{ ContextMgmt_param_fdir_sw_att0c_max, E_PARAM_ID_ATT0M_C, Max },
	{ ContextMgmt_param_fdir_sw_att1c_min, E_PARAM_ID_ATT1M_C, Min },
	{ ContextMgmt_param_fdir_sw_att1c_max, E_PARAM_ID_ATT1M_C, Max },
	{ ContextMgmt_param_fdir_sw_att2c_min, E_PARAM_ID_ATT2M_C, Min },
	{ ContextMgmt_param_fdir_sw_att2c_max, E_PARAM_ID_ATT2M_C, Max },
	{ ContextMgmt_param_fdir_hw_attc, E_PARAM_ID_CONFIG_ATT_CURRENT_THRESHOLD, Value },
	{ ContextMgmt_param_fdir_sw_attv_min, E_PARAM_ID_ATT_V, Min },
	{ ContextMgmt_param_fdir_sw_attv_max, E_PARAM_ID_ATT_V, Max },
	{ ContextMgmt_param_fdir_hw_attv, E_PARAM_ID_CONFIG_ATT_VOLTAGE_THRESHOLD, Value },
	{ ContextMgmt_param_fdir_sw_hw01_min, E_PARAM_ID_PSU_HV_01, Min },
	{ ContextMgmt_param_fdir_sw_hw01_max, E_PARAM_ID_PSU_HV_01, Max },
	{ ContextMgmt_param_fdir_hw_hw01, E_PARAM_ID_CONFIG_PSU_HV01_THRESHOLD, Value },
	{ ContextMgmt_param_fdir_sw_hw02_min, E_PARAM_ID_PSU_HV_17, Min },
	{ ContextMgmt_param_fdir_sw_hw02_max, E_PARAM_ID_PSU_HV_17, Max },
	{ ContextMgmt_param_fdir_hw_hw02, E_PARAM_ID_CONFIG_PSU_HV17_THRESHOLD, Value },
	{ ContextMgmt_param_fdir_sw_2v9v_min, E_PARAM_ID_ADC_SELFCHECK_2V9, Min },
	{ ContextMgmt_param_fdir_sw_2v9v_max, E_PARAM_ID_ADC_SELFCHECK_2V9, Max },
	{ ContextMgmt_param_fdir_sw_2v5v_min, E_PARAM_ID_ADC_SELFCHECK_2V5, Min },
	{ ContextMgmt_param_fdir_sw_2v5v_max, E_PARAM_ID_ADC_SELFCHECK_2V5, Max },
	{ ContextMgmt_param_fdir_sw_1v5v_min, E_PARAM_ID_ADC_SELFCHECK_1V5, Min },
	{ ContextMgmt_param_fdir_sw_1v5v_max, E_PARAM_ID_ADC_SELFCHECK_1V5, Max },
	{ ContextMgmt_param_fdir_sw_spw0v_min, E_PARAM_ID_SPW_VOLTAGE_MAIN, Min },
	{ ContextMgmt_param_fdir_sw_spw0v_max, E_PARAM_ID_SPW_VOLTAGE_MAIN, Max },
	{ ContextMgmt_param_fdir_sw_spw1v_min, E_PARAM_ID_SPW_VOLTAGE_REDUNDANT, Min },
	{ ContextMgmt_param_fdir_sw_spw1v_max, E_PARAM_ID_SPW_VOLTAGE_REDUNDANT, Max },
	{ ContextMgmt_param_fdir_sw_asp_vsensa_min, E_PARAM_ID_ASP_VSENSA_V, Min },
	{ ContextMgmt_param_fdir_sw_asp_vsensa_max, E_PARAM_ID_ASP_VSENSA_V, Max },
	{ ContextMgmt_param_fdir_sw_asp_vsensb_min, E_PARAM_ID_ASP_VSENSB_V, Min },
	{ ContextMgmt_param_fdir_sw_asp_vsensb_max, E_PARAM_ID_ASP_VSENSB_V, Max },
	{ ContextMgmt_param_fdir_sw_asp_refa_min, E_PARAM_ID_ASP_REF_2V5A_V, Min },
	{ ContextMgmt_param_fdir_sw_asp_refa_max, E_PARAM_ID_ASP_REF_2V5A_V, Max },
	{ ContextMgmt_param_fdir_sw_asp_refb_min, E_PARAM_ID_ASP_REF_2V5B_V, Min },
	{ ContextMgmt_param_fdir_sw_asp_refb_max, E_PARAM_ID_ASP_REF_2V5B_V, Max },
	{ ContextMgmt_param_fdir_sw_asp_photoA0_min, E_PARAM_ID_ASP_PHOTOA0_V, Min },
	{ ContextMgmt_param_fdir_sw_asp_photoA0_max, E_PARAM_ID_ASP_PHOTOA0_V, Max },
	{ ContextMgmt_param_fdir_sw_asp_photoA1_min, E_PARAM_ID_ASP_PHOTOA1_V, Min },
	{ ContextMgmt_param_fdir_sw_asp_photoA1_max, E_PARAM_ID_ASP_PHOTOA1_V, Max },
	{ ContextMgmt_param_fdir_sw_asp_photoB0_min, E_PARAM_ID_ASP_PHOTOB0_V, Min },
	{ ContextMgmt_param_fdir_sw_asp_photoB0_max, E_PARAM_ID_ASP_PHOTOB0_V, Max },
	{ ContextMgmt_param_fdir_sw_asp_photoB1_min, E_PARAM_ID_ASP_PHOTOB1_V, Min },
	{ ContextMgmt_param_fdir_sw_asp_photoB1_max, E_PARAM_ID_ASP_PHOTOB1_V, Max },
	{ ContextMgmt_param_fdir_sw_fpgat_min, E_PARAM_ID_IDPU_TEMP_FPGA, Min },
	{ ContextMgmt_param_fdir_sw_fpgat_max, E_PARAM_ID_IDPU_TEMP_FPGA, Max },
	{ ContextMgmt_param_fdir_sw_pcbt_min, E_PARAM_ID_IDPU_TEMP_PCB, Min },
	{ ContextMgmt_param_fdir_sw_pcbt_max, E_PARAM_ID_IDPU_TEMP_PCB, Max },
	{ ContextMgmt_param_fdir_sw_tim01t_min, E_PARAM_ID_ASP_TIM01, Min },
	{ ContextMgmt_param_fdir_sw_tim01t_max, E_PARAM_ID_ASP_TIM01, Max },
	{ ContextMgmt_param_fdir_sw_tim02t_min, E_PARAM_ID_ASP_TIM02, Min },
	{ ContextMgmt_param_fdir_sw_tim02t_max, E_PARAM_ID_ASP_TIM02, Max },
	{ ContextMgmt_param_fdir_sw_tim03t_min, E_PARAM_ID_ASP_TIM03, Min },
	{ ContextMgmt_param_fdir_sw_tim03t_max, E_PARAM_ID_ASP_TIM03, Max },
	{ ContextMgmt_param_fdir_sw_tim04t_min, E_PARAM_ID_ASP_TIM04, Min },
	{ ContextMgmt_param_fdir_sw_tim04t_max, E_PARAM_ID_ASP_TIM04, Max },
	{ ContextMgmt_param_fdir_sw_tim05t_min, E_PARAM_ID_ASP_TIM05, Min },
	{ ContextMgmt_param_fdir_sw_tim05t_max, E_PARAM_ID_ASP_TIM05, Max },
	{ ContextMgmt_param_fdir_sw_tim06t_min, E_PARAM_ID_ASP_TIM06, Min },
	{ ContextMgmt_param_fdir_sw_tim06t_max, E_PARAM_ID_ASP_TIM06, Max },
	{ ContextMgmt_param_fdir_sw_tim07t_min, E_PARAM_ID_ASP_TIM07, Min },
	{ ContextMgmt_param_fdir_sw_tim07t_max, E_PARAM_ID_ASP_TIM07, Max },
	{ ContextMgmt_param_fdir_sw_tim08t_min, E_PARAM_ID_ASP_TIM08, Min },
	{ ContextMgmt_param_fdir_sw_tim08t_max, E_PARAM_ID_ASP_TIM08, Max },
	{ ContextMgmt_param_fdir_sw_det01t_min, E_PARAM_ID_DET_Q1_T, Min },
	{ ContextMgmt_param_fdir_sw_det01t_max, E_PARAM_ID_DET_Q1_T, Max },
	{ ContextMgmt_param_fdir_sw_det02t_min, E_PARAM_ID_DET_Q2_T, Min },
	{ ContextMgmt_param_fdir_sw_det02t_max, E_PARAM_ID_DET_Q2_T, Max },
	{ ContextMgmt_param_fdir_sw_det03t_min, E_PARAM_ID_DET_Q3_T, Min },
	{ ContextMgmt_param_fdir_sw_det03t_max, E_PARAM_ID_DET_Q3_T, Max },
	{ ContextMgmt_param_fdir_sw_det04t_min, E_PARAM_ID_DET_Q4_T, Min },
	{ ContextMgmt_param_fdir_sw_det04t_max, E_PARAM_ID_DET_Q4_T, Max },
	{ ContextMgmt_param_fdir_sw_attt_min, E_PARAM_ID_ATT_T, Min },
	{ ContextMgmt_param_fdir_sw_attt_max, E_PARAM_ID_ATT_T, Max },
	{ ContextMgmt_param_fdir_meas_trig_psut, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_PSU_TEMP, Value },
	{ ContextMgmt_param_fdir_meas_trig_pcbt, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_PCB_TEMP, Value },
	{ ContextMgmt_param_fdir_meas_trig_fpgat, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_FPGA_TEMP, Value },
	{ ContextMgmt_param_fdir_meas_trig_3v3c, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_3V3_C, Value },
	{ ContextMgmt_param_fdir_meas_trig_2v5c, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_2V5_C, Value },
	{ ContextMgmt_param_fdir_meas_trig_1v5c, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_1V5_C, Value },
	{ ContextMgmt_param_fdir_meas_trig_spwc, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_SPW_C, Value },
	{ ContextMgmt_param_fdir_meas_trig_spw0v, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_SPW0_V, Value },
	{ ContextMgmt_param_fdir_meas_trig_spw1v, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_SPW1_V, Value },
	{ ContextMgmt_param_fdir_meas_trig_1v5v, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_1V5_V, Value },
	{ ContextMgmt_param_fdir_meas_trig_2v5v, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_2V5_V, Value },
	{ ContextMgmt_param_fdir_meas_trig_2v9v, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_2V9_V, Value },
	{ ContextMgmt_param_fdir_meas_trig_attv, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ATT_V, Value },
	{ ContextMgmt_param_fdir_meas_trig_attc, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ATT_C, Value },
	{ ContextMgmt_param_fdir_meas_trig_attt, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ATT_T, Value },
	{ ContextMgmt_param_fdir_meas_trig_hv01, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_HV01, Value },
	{ ContextMgmt_param_fdir_meas_trig_hv02, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_HV17, Value },
	{ ContextMgmt_param_fdir_meas_trig_detc, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_DET_C, Value },
	{ ContextMgmt_param_fdir_meas_trig_detq1t, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_DET_Q1_T, Value },
	{ ContextMgmt_param_fdir_meas_trig_detq2t, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_DET_Q2_T, Value },
	{ ContextMgmt_param_fdir_meas_trig_detq3t, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_DET_Q3_T, Value },
	{ ContextMgmt_param_fdir_meas_trig_detq4t, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_DET_Q4_T, Value },
	{ ContextMgmt_param_fdir_meas_trig_asp_refa, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ASP_REFA_V, Value },
	{ ContextMgmt_param_fdir_meas_trig_asp_refb, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ASP_REFB_V, Value },
	{ ContextMgmt_param_fdir_meas_trig_tim01t, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ASP_TIM01, Value },
	{ ContextMgmt_param_fdir_meas_trig_tim02t, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ASP_TIM02, Value },
	{ ContextMgmt_param_fdir_meas_trig_tim03t, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ASP_TIM03, Value },
	{ ContextMgmt_param_fdir_meas_trig_tim04t, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ASP_TIM04, Value },
	{ ContextMgmt_param_fdir_meas_trig_tim05t, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ASP_TIM05, Value },
	{ ContextMgmt_param_fdir_meas_trig_tim06t, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ASP_TIM06, Value },
	{ ContextMgmt_param_fdir_meas_trig_tim07t, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ASP_TIM07, Value },
	{ ContextMgmt_param_fdir_meas_trig_tim08t, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ASP_TIM08, Value },
	{ ContextMgmt_param_fdir_meas_trig_asp_vsensa, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ASP_VSENSA, Value },
	{ ContextMgmt_param_fdir_meas_trig_asp_vsensb, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ASP_VSENSB, Value },
	{ ContextMgmt_param_fdir_meas_trig_asp_photoa0, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ASP_PHOTOA0, Value },
	{ ContextMgmt_param_fdir_meas_trig_asp_photoa1, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ASP_PHOTOA1, Value },
	{ ContextMgmt_param_fdir_meas_trig_asp_photob0, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ASP_PHOTOB0, Value },
	{ ContextMgmt_param_fdir_meas_trig_asp_photob1, E_PARAM_ID_HKMON_OUT_OF_BOUNDS_TRIGGERED_ASP_PHOTOB1, Value },
	{ ContextMgmt_param_fdir_seu_ignore_flag, E_PARAM_ID_SEU_IGNORE_GROUP_FLAGS, Value },
	{ ContextMgmt_param_fdir_enabled_dete_quarter, E_PARAM_ID_DETECTOR_QUARTERS_POWER, Value },
	{ ContextMgmt_param_fdir_att_number_moves, E_PARAM_ID_FDIR_ATT_TOTAL_COUNTER, Value },
	{ ContextMgmt_param_fdir_att_N1, E_PARAM_ID_FDIR_ATT_LIMIT_N1, Value },
	{ ContextMgmt_param_fdir_att_T1, E_PARAM_ID_FDIR_ATT_LIMIT_T1, Value },
	{ ContextMgmt_param_fdir_att_N2, E_PARAM_ID_FDIR_ATT_LIMIT_N2, Value },
	{ ContextMgmt_param_fdir_att_T2, E_PARAM_ID_FDIR_ATT_LIMIT_T2, Value },
	{ ContextMgmt_param_fdir_asic_verif_disabled_dete_mask, E_PARAM_ID_CALISTE_IGNORE_FLAGS, Value },
	{ ContextMgmt_param_fdir_asic_verif_period, E_PARAM_ID_ASIC_VERIFICATION_PERIOD, Value },
	{ ContextMgmt_param_fdir_hv01_depolarisation_period, E_PARAM_ID_HV_RESET_INTERVAL_1, Value },
	{ ContextMgmt_param_fdir_hv02_depolarisation_period, E_PARAM_ID_HV_RESET_INTERVAL_2, Value },
	{ ContextMgmt_param_fdir_hv01_depolarisation_duration, E_PARAM_ID_HV_RESET_DURATION_1, Value },
	{ ContextMgmt_param_fdir_hv02_depolarisation_duration, E_PARAM_ID_HV_RESET_DURATION_2, Value },
	{ ContextMgmt_param_fdir_enabled_function_mask, E_PARAM_ID_FDIR_ENABLED_FUNCTIONS, Value },
	{ ContextMgmt_param_fdir_enabled_current_function_checks, E_PARAM_ID_FDIR_ENABLED_CURRENT_CHECK, Value },
	{ ContextMgmt_param_fdir_enabled_voltage_function_checks, E_PARAM_ID_FDIR_ENABLED_VOLTAGE_CHECK, Value },
	{ ContextMgmt_param_fdir_enabled_temperature_function_checks, E_PARAM_ID_FDIR_ENABLED_TEMPERATURE_CHECK, Value },
	{ ContextMgmt_param_config_hv01_line_enabled, E_PARAM_ID_HV_01_16_State, Value },
	{ ContextMgmt_param_config_hv02_line_enabled, E_PARAM_ID_HV_17_32_State, Value },
	{ ContextMgmt_param_config_hv01_value, E_PARAM_ID_HV_01_16_Pwm, Value },
	{ ContextMgmt_param_config_hv02_value, E_PARAM_ID_HV_17_32_Pwm, Value },
	{ ContextMgmt_param_config_spw_ocp_state, E_PARAM_ID_CONFIG_SPW_ENABLE_OVC, Value },
	{ ContextMgmt_param_config_det_ocp_state, E_PARAM_ID_CONFIG_DET_ENABLE_OCP, Value },
	{ ContextMgmt_param_config_att_ocp_state, E_PARAM_ID_CONFIG_ATT_ENABLE_OCP, Value },
	{ ContextMgmt_param_config_1v5_ocp_state, E_PARAM_ID_CONFIG_PSU_1V5_ENABLE_OCP, Value },
	{ ContextMgmt_param_config_2v5_ocp_state, E_PARAM_ID_CONFIG_PSU_2V5_ENABLE_OCP, Value },
	{ ContextMgmt_param_config_3v3_ocp_state, E_PARAM_ID_CONFIG_PSU_3V3_ENABLE_OCP, Value },
	{ ContextMgmt_param_config_att_ovp_state, E_PARAM_ID_CONFIG_ATT_ENABLE_OVP, Value },
	{ ContextMgmt_param_config_hv1_ovp_state, E_PARAM_ID_CONFIG_PSU_HV01_ENABLE_OVP, Value },
	{ ContextMgmt_param_config_hv2_ovp_state, E_PARAM_ID_CONFIG_PSU_HV17_ENABLE_OVP, Value },
	{ ContextMgmt_param_config_asp_fpga_readout_per_sum, E_PARAM_ID_ASPECT_SUMMED_VALUES, Value },
	{ ContextMgmt_param_config_att_max_pwm, E_PARAM_ID_ATT_MAX_PWM_LEVEL, Value },
	{ ContextMgmt_param_config_att_nom_pwm, E_PARAM_ID_ATT_NOMINAL_PWM_LEVEL, Value },
	{ ContextMgmt_param_config_fsw_s20_reaction_state, E_PARAM_ID_CONFIG_FSW_REACTION_TO_SERVICE_20, Value },
	{ ContextMgmt_param_config_fsw_enable_tm51, E_PARAM_ID_CONFIG_FSW_RECONFIGURATION_INFO_TM51, Value },
	{ ContextMgmt_param_config_sdram_prescaler, E_PARAM_ID_CONFIG_SDRAM_PRESCALER, Value },
	{ ContextMgmt_param_config_rotb_prescaler, E_PARAM_ID_CONFIG_ROTB_PRESCALER, Value },
	{ ContextMgmt_param_config_spw_transient_duration, E_PARAM_ID_SPW_LINK_PROBLEM_TRANSIENT_DURATION_MS, Value },
	{ ContextMgmt_param_calib_cyclic_state, E_PARAM_ID_CALIB_CONTINUOUS_ACQUISITION, Value },
	{ ContextMgmt_param_calib_tq, E_PARAM_ID_CALIB_QUIET_TIME, Value },
	{ ContextMgmt_param_calib_detemask, E_PARAM_ID_CALIB_DETECTOR_MASK, Value },
	{ ContextMgmt_param_calib_ta, E_PARAM_ID_CALIB_MAX_INTEGRATION, Value },
	{ ContextMgmt_param_calib_formatting_subspectra_mask, E_PARAM_ID_CALIB_SUBSPECT_FORMATTING_MASK, Value },
	{ ContextMgmt_param_calib_formatting_subspectrum_1, E_PARAM_ID_CALIB_SUBSPECTRA1, Value },
	{ ContextMgmt_param_calib_formatting_subspectrum_2, E_PARAM_ID_CALIB_SUBSPECTRA2, Value },
	{ ContextMgmt_param_calib_formatting_subspectrum_3, E_PARAM_ID_CALIB_SUBSPECTRA3, Value },
	{ ContextMgmt_param_calib_formatting_subspectrum_4, E_PARAM_ID_CALIB_SUBSPECTRA4, Value },
	{ ContextMgmt_param_calib_formatting_subspectrum_5, E_PARAM_ID_CALIB_SUBSPECTRA5, Value },
	{ ContextMgmt_param_calib_formatting_subspectrum_6, E_PARAM_ID_CALIB_SUBSPECTRA6, Value },
	{ ContextMgmt_param_calib_formatting_subspectrum_7, E_PARAM_ID_CALIB_SUBSPECTRA7, Value },
	{ ContextMgmt_param_calib_formatting_subspectrum_8, E_PARAM_ID_CALIB_SUBSPECTRA8, Value },
	{ ContextMgmt_param_calib_formatting_detemask, E_PARAM_ID_CALIB_DETE_FORMATTING_MASK, Value },
	{ ContextMgmt_param_calib_formatting_bit_reduction_flag, E_PARAM_ID_CALIB_BIN_REDUCTION_OPTION, Value },
	{ ContextMgmt_param_calib_formatting_pixelmask, E_PARAM_ID_CALIB_PIXEL_FORMATTING_MASK, Value },
	{ ContextMgmt_param_ql_nominal_period, E_PARAM_ID_NOMINAL_QL_PERIOD, Value },
	{ ContextMgmt_param_qlbg_enabled, E_PARAM_ID_QL_BGMON_ENABLE_ALGO, Value },
	{ ContextMgmt_param_qlbg_enabled_tm, E_PARAM_ID_QL_BGMON_ENABLE_TM, Value },
	{ ContextMgmt_param_qlbg_default_value_range_1, E_PARAM_ID_QL_BGMON_DEFAULT_R0, Value },
	{ ContextMgmt_param_qlbg_default_value_range_2, E_PARAM_ID_QL_BGMON_DEFAULT_R1, Value },
	{ ContextMgmt_param_qlbg_default_value_range_3, E_PARAM_ID_QL_BGMON_DEFAULT_R2, Value },
	{ ContextMgmt_param_qlbg_default_value_range_4, E_PARAM_ID_QL_BGMON_DEFAULT_R3, Value },
	{ ContextMgmt_param_qlbg_default_value_range_5, E_PARAM_ID_QL_BGMON_DEFAULT_R4, Value },
	{ ContextMgmt_param_qlbg_default_value_range_6, E_PARAM_ID_QL_BGMON_DEFAULT_R5, Value },
	{ ContextMgmt_param_qlbg_default_value_range_7, E_PARAM_ID_QL_BGMON_DEFAULT_R6, Value },
	{ ContextMgmt_param_qlbg_default_value_range_8, E_PARAM_ID_QL_BGMON_DEFAULT_R7, Value },
	{ ContextMgmt_param_qlbg_ql_integration_per_datum, E_PARAM_ID_QL_BGMON_NUMBER_OF_INTEGRATIONS, Value },
	{ ContextMgmt_param_qlbg_compression_scheme_counts, E_PARAM_ID_QL_BGMON_COMPRESSION_SCHEMA_COUNTS, Value },
	{ ContextMgmt_param_qlbg_compression_scheme_triggers, E_PARAM_ID_QL_BGMON_COMPRESSION_SCHEMA_TRIGGERS, Value },
	{ ContextMgmt_param_qlbg_energy_bin_edge_mask_upper_bit, E_PARAM_ID_QL_BGMON_ENERGY_BIN_MASK1, Value },
	{ ContextMgmt_param_qlbg_energy_bin_edge_mask_lower_bits, E_PARAM_ID_QL_BGMON_ENERGY_BIN_MASK2, Value },
	{ ContextMgmt_param_qllc_energy_bin_edge_mask_upper_bit, E_PARAM_ID_QL_LIGHTCURVE_ENERGY_BIN_MASK1, Value },
	{ ContextMgmt_param_qllc_energy_bin_edge_mask_lower_bits, E_PARAM_ID_QL_LIGHTCURVE_ENERGY_BIN_MASK2, Value },
	{ ContextMgmt_param_qllc_enable_tm, E_PARAM_ID_QL_LIGHTCURVE_ENABLE_TM, Value },
	{ ContextMgmt_param_qllc_ql_integration_per_datum, E_PARAM_ID_QL_LIGHTCURVE_NUMBER_OF_INTEGRATIONS, Value },
	{ ContextMgmt_param_qllc_compression_scheme_counts, E_PARAM_ID_QL_LIGHTCURVE_COMPRESSION_SCHEMA_COUNTS, Value },
	{ ContextMgmt_param_qllc_compression_scheme_triggers, E_PARAM_ID_QL_LIGHTCURVE_COMPRESSION_SCHEMA_TRIGGERS, Value },
	{ ContextMgmt_param_qllc_detemask, E_PARAM_ID_QL_LIGHTCURVE_DETE_MASK, Value },
	{ ContextMgmt_param_qllc_pixemask, E_PARAM_ID_QL_LIGHTCURVE_PIXE_MASK, Value },
	{ ContextMgmt_param_qlfdet_pixemask, E_PARAM_ID_QL_FLAREDET_PIXE_MASK, Value },
	{ ContextMgmt_param_qlfdet_thermal_energy_mask, E_PARAM_ID_QL_FLAREDET_THERMAL_ENERGY_MASK, Value },
	{ ContextMgmt_param_qlfdet_nonthermal_energy_mask, E_PARAM_ID_QL_FLAREDET_NONTHERMAL_ENERGY_MASK, Value },
	{ ContextMgmt_param_qlfdet_kb, E_PARAM_ID_QL_FLAREDET_KB, Value },
	{ ContextMgmt_param_qlfdet_thermal_factor_rcr1, E_PARAM_ID_QL_FLAREDET_F_E1_R0, Value },
	{ ContextMgmt_param_qlfdet_thermal_factor_rcr2, E_PARAM_ID_QL_FLAREDET_F_E1_R1, Value },
	{ ContextMgmt_param_qlfdet_thermal_factor_rcr3, E_PARAM_ID_QL_FLAREDET_F_E1_R2, Value },
	{ ContextMgmt_param_qlfdet_thermal_factor_rcr4, E_PARAM_ID_QL_FLAREDET_F_E1_R3, Value },
	{ ContextMgmt_param_qlfdet_thermal_factor_rcr5, E_PARAM_ID_QL_FLAREDET_F_E1_R4, Value },
	{ ContextMgmt_param_qlfdet_thermal_factor_rcr6, E_PARAM_ID_QL_FLAREDET_F_E1_R5, Value },
	{ ContextMgmt_param_qlfdet_thermal_factor_rcr7, E_PARAM_ID_QL_FLAREDET_F_E1_R6, Value },
	{ ContextMgmt_param_qlfdet_thermal_factor_rcr8, E_PARAM_ID_QL_FLAREDET_F_E1_R7, Value },
	{ ContextMgmt_param_qlfdet_nonthermal_factor_rcr1, E_PARAM_ID_QL_FLAREDET_F_E2_R0, Value },
	{ ContextMgmt_param_qlfdet_nonthermal_factor_rcr2, E_PARAM_ID_QL_FLAREDET_F_E2_R1, Value },
	{ ContextMgmt_param_qlfdet_nonthermal_factor_rcr3, E_PARAM_ID_QL_FLAREDET_F_E2_R2, Value },
	{ ContextMgmt_param_qlfdet_nonthermal_factor_rcr4, E_PARAM_ID_QL_FLAREDET_F_E2_R3, Value },
	{ ContextMgmt_param_qlfdet_nonthermal_factor_rcr5, E_PARAM_ID_QL_FLAREDET_F_E2_R4, Value },
	{ ContextMgmt_param_qlfdet_nonthermal_factor_rcr6, E_PARAM_ID_QL_FLAREDET_F_E2_R5, Value },
	{ ContextMgmt_param_qlfdet_nonthermal_factor_rcr7, E_PARAM_ID_QL_FLAREDET_F_E2_R6, Value },
	{ ContextMgmt_param_qlfdet_nonthermal_factor_rcr8, E_PARAM_ID_QL_FLAREDET_F_E2_R7, Value },
	{ ContextMgmt_param_qlfdet_k, E_PARAM_ID_QL_FLAREDET_KREL, Value },
	{ ContextMgmt_param_qlfdet_kp, E_PARAM_ID_QL_FLAREDET_KRELP, Value },
	{ ContextMgmt_param_qlfdet_kpp, E_PARAM_ID_QL_FLAREDET_KRELPP, Value },
	{ ContextMgmt_param_qlfdet_timescale_short, E_PARAM_ID_QL_FLAREDET_TIMESCALE1, Value },
	{ ContextMgmt_param_qlfdet_timescale_long, E_PARAM_ID_QL_FLAREDET_TIMESCALE2, Value },
	{ ContextMgmt_param_qlfdet_init_thermal_cbc, E_PARAM_ID_QL_FLAREDET_CBCINIT_THERMAL, Value },
	{ ContextMgmt_param_qlfdet_init_nonthermal_cbc, E_PARAM_ID_QL_FLAREDET_CBCINIT_NONTHERMAL, Value },
	{ ContextMgmt_param_qlfdet_cfmin, E_PARAM_ID_QL_FLAREDET_CFMIN, Value },
	{ ContextMgmt_param_qlfdet_threshold_thermal_B1, E_PARAM_ID_QL_FLAREDET_THERMAL_THRESHOLD_B1, Value },
	{ ContextMgmt_param_qlfdet_threshold_thermal_C1, E_PARAM_ID_QL_FLAREDET_THERMAL_THRESHOLD_C1, Value },
	{ ContextMgmt_param_qlfdet_threshold_thermal_M1, E_PARAM_ID_QL_FLAREDET_THERMAL_THRESHOLD_M1, Value },
	{ ContextMgmt_param_qlfdet_threshold_thermal_X1, E_PARAM_ID_QL_FLAREDET_THERMAL_THRESHOLD_X1, Value },
	{ ContextMgmt_param_qlfdet_threshold_nonthermal_weak, E_PARAM_ID_QL_FLAREDET_NONTHERMAL_THRESHOLD_WEAK, Value },
	{ ContextMgmt_param_qlfdet_threshold_nonthermal_significant, E_PARAM_ID_QL_FLAREDET_NONTHERMAL_THRESHOLD_SIGNIF, Value },
	{ ContextMgmt_param_qlfdetfloc_enable_tm, E_PARAM_ID_QL_FLARE_ENABLE_TM, Value },
	{ ContextMgmt_param_qlfdet_ql_integration_per_datum, E_PARAM_ID_QL_FLAREDET_NUMBER_OF_INTEGRATIONS, Value },
	{ ContextMgmt_param_qlffloc_ql_integration_per_datum, E_PARAM_ID_QL_FLARELOC_NUMBER_OF_INTEGRATIONS, Value },
	{ ContextMgmt_param_qlfloc_dete_mask, E_PARAM_ID_QL_FLARELOC_DET_MASK, Value },
	{ ContextMgmt_param_qlfloc_energy_mask, E_PARAM_ID_QL_FLARELOC_ENERGY_MASK, Value },
	{ ContextMgmt_param_qlfloc_sky_table_id, E_PARAM_ID_CONFIG_CURRENT_SKY_LUT_ID, Value },
	{ ContextMgmt_param_qlfloc_L1, E_PARAM_ID_QL_FLARELOC_V1, Value },
	{ ContextMgmt_param_qlfloc_L2, E_PARAM_ID_QL_FLARELOC_V2, Value },
	{ ContextMgmt_param_qlfloc_k, E_PARAM_ID_QL_FLARELOC_K, Value },
	{ ContextMgmt_param_qlfloc_kp, E_PARAM_ID_QL_FLARELOC_KP, Value },
	{ ContextMgmt_param_qlfloc_kpp, E_PARAM_ID_QL_FLARELOC_KPP, Value },
	{ ContextMgmt_param_qlfloc_kppp, E_PARAM_ID_QL_FLARELOC_KPPP, Value },
	{ ContextMgmt_param_qlfloc_k0, E_PARAM_ID_QL_FLARELOC_K0, Value },
	{ ContextMgmt_param_qlfloc_k1, E_PARAM_ID_QL_FLARELOC_K1, Value },
	{ ContextMgmt_param_qlfloc_k2, E_PARAM_ID_QL_FLARELOC_K2, Value },
	{ ContextMgmt_param_qlfloc_dx, E_PARAM_ID_QL_FLARELOC_DX, Value },
	{ ContextMgmt_param_qlfloc_dy, E_PARAM_ID_QL_FLARELOC_DY, Value },
	{ ContextMgmt_param_qldmon_active_detector_mask, E_PARAM_ID_QL_DETPERF_ACTIVE_DETE_MASK, Value },
	{ ContextMgmt_param_qldmon_energy_mask, E_PARAM_ID_QL_DETPERF_ENERGY_MASK, Value },
	{ ContextMgmt_param_qldmon_ql_integration_per_datum, E_PARAM_ID_QL_DETPERF_NUMBER_OF_INTEGRATIONS, Value },
	{ ContextMgmt_param_qldmon_kbad, E_PARAM_ID_QL_DETPERF_KBAD, Value },
	{ ContextMgmt_param_qldmon_rbad, E_PARAM_ID_QL_DETPERF_CBAD, Value },
	{ ContextMgmt_param_qldmon_nbad, E_PARAM_ID_QL_DETPERF_NBAD, Value },
	{ ContextMgmt_param_qldmon_nrep, E_PARAM_ID_QL_DETPERF_NREP, Value },
	{ ContextMgmt_param_qlsp_detemask, E_PARAM_ID_QL_SPECTRUM_DETE_MASK, Value },
	{ ContextMgmt_param_qlsp_pixemask, E_PARAM_ID_QL_SPECTRUM_PIXE_MASK, Value },
	{ ContextMgmt_param_qlsp_ql_integrations_per_datum, E_PARAM_ID_QL_SPECTRUM_NUMBER_OF_INTEGRATIONS, Value },
	{ ContextMgmt_param_qlsp_enable_tm, E_PARAM_ID_QL_SPECTRUM_ENABLE_TM, Value },
	{ ContextMgmt_param_qlsp_compression_scheme_counts, E_PARAM_ID_QL_SPECTRUM_COMPRESSION_SCHEMA_COUNTS, Value },
	{ ContextMgmt_param_qlsp_compression_scheme_triggers, E_PARAM_ID_QL_SPECTRUM_COMPRESSION_SCHEMA_TRIGGERS, Value },
	{ ContextMgmt_param_qlvar_detemask, E_PARAM_ID_QL_VARIANCE_DETE_MASK, Value },
	{ ContextMgmt_param_qlvar_enemask, E_PARAM_ID_QL_VARIANCE_ENE_MASK, Value },
	{ ContextMgmt_param_qlvar_pixemask, E_PARAM_ID_QL_VARIANCE_PIXE_MASK, Value },
	{ ContextMgmt_param_qlvar_enable_tm, E_PARAM_ID_QL_VARIANCE_ENABLE_TM, Value },
	{ ContextMgmt_param_qlvar_compression_scheme_counts, E_PARAM_ID_QL_VARIANCE_COMPRESSION_SCHEMA, Value },
	{ ContextMgmt_param_qlrcr_enabled, E_PARAM_ID_RCR_ENABLED, Value },
	{ ContextMgmt_param_qlrcr_group_mask, E_PARAM_ID_RCR_GROUP_MASK, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr0, E_PARAM_ID_RCR_PIXEL_0, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr1, E_PARAM_ID_RCR_PIXEL_1, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr2_north, E_PARAM_ID_RCR_PIXEL_2N, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr2_south, E_PARAM_ID_RCR_PIXEL_2S, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr3_north_1, E_PARAM_ID_RCR_PIXEL_3N1, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr3_north_2, E_PARAM_ID_RCR_PIXEL_3N2, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr3_south_1, E_PARAM_ID_RCR_PIXEL_3S1, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr3_south_2, E_PARAM_ID_RCR_PIXEL_3S2, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr4_north_1, E_PARAM_ID_RCR_PIXEL_4N1, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr4_north_2, E_PARAM_ID_RCR_PIXEL_4N2, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr4_north_3, E_PARAM_ID_RCR_PIXEL_4N3, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr4_north_4, E_PARAM_ID_RCR_PIXEL_4N4, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr4_south_1, E_PARAM_ID_RCR_PIXEL_4S1, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr4_south_2, E_PARAM_ID_RCR_PIXEL_4S2, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr4_south_3, E_PARAM_ID_RCR_PIXEL_4S3, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr4_south_4, E_PARAM_ID_RCR_PIXEL_4S4, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr5, E_PARAM_ID_RCR_PIXEL_5, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr6_1, E_PARAM_ID_RCR_PIXEL_6_1, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr6_2, E_PARAM_ID_RCR_PIXEL_6_2, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr7_1, E_PARAM_ID_RCR_PIXEL_7_1, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr7_2, E_PARAM_ID_RCR_PIXEL_7_2, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr7_3, E_PARAM_ID_RCR_PIXEL_7_3, Value },
	{ ContextMgmt_param_qlrcr_pixelmask_rcr7_4, E_PARAM_ID_RCR_PIXEL_7_4, Value },
	{ ContextMgmt_param_qlrcr_regime2state_lut, E_PARAM_ID_RCR_REGIME_TO_STATE, Value },
	{ ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr0, E_PARAM_ID_RCR_PIXEL_B0, Value },
	{ ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr1, E_PARAM_ID_RCR_PIXEL_B1, Value },
	{ ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr2, E_PARAM_ID_RCR_PIXEL_B2, Value },
	{ ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr3, E_PARAM_ID_RCR_PIXEL_B3, Value },
	{ ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr4, E_PARAM_ID_RCR_PIXEL_B4, Value },
	{ ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr5, E_PARAM_ID_RCR_PIXEL_B5, Value },
	{ ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr6, E_PARAM_ID_RCR_PIXEL_B6, Value },
	{ ContextMgmt_param_qlrcr_bckg_pixel_mask_rcr7, E_PARAM_ID_RCR_PIXEL_B7, Value },
	{ ContextMgmt_param_qlrcr_L0, E_PARAM_ID_RCR_L0, Value },
	{ ContextMgmt_param_qlrcr_L1, E_PARAM_ID_RCR_L1, Value },
	{ ContextMgmt_param_qlrcr_L2, E_PARAM_ID_RCR_L2, Value },
	{ ContextMgmt_param_qlrcr_L3, E_PARAM_ID_RCR_L3, Value },
	{ ContextMgmt_param_accum_max_duration, E_PARAM_ID_NOMINAL_ACCU_MAX_INTEGRATION, Value },
	{ ContextMgmt_param_accum_min_duration, E_PARAM_ID_NOMINAL_ACCU_MIN_INTEGRATION, Value },
	{ ContextMgmt_param_accum_max_counts, E_PARAM_ID_NOMINAL_ACCU_MAX_COUNTS, Value },
	{ ContextMgmt_param_accum_sum_e_mask, E_PARAM_ID_NOMINAL_SUMEMASK, Value },
	{ ContextMgmt_param_accum_sum_d_mask, E_PARAM_ID_NOMINAL_SUMDMASK, Value },
	{ ContextMgmt_param_data_level, E_PARAM_ID_DEFAULT_DATA_COMPRESSION, Value },
	{ ContextMgmt_param_data_l0_dete_mask, E_PARAM_ID_DETECTOR_MASK_L0, Value },
	{ ContextMgmt_param_data_l0_pixe_mask, E_PARAM_ID_PIXEL_MASK_L0, Value },
	{ ContextMgmt_param_data_l1_rcr1_pixe_mask, E_PARAM_ID_PIXEL_MASK_L1R0, Value },
	{ ContextMgmt_param_data_l1_rcr2_pixe_mask, E_PARAM_ID_PIXEL_MASK_L1R1, Value },
	{ ContextMgmt_param_data_l1_rcr3_pixe_mask, E_PARAM_ID_PIXEL_MASK_L1R2, Value },
	{ ContextMgmt_param_data_l1_rcr4_pixe_mask, E_PARAM_ID_PIXEL_MASK_L1R3, Value },
	{ ContextMgmt_param_data_l1_rcr5_pixe_mask, E_PARAM_ID_PIXEL_MASK_L1R4, Value },
	{ ContextMgmt_param_data_l1_rcr6_pixe_mask, E_PARAM_ID_PIXEL_MASK_L1R5, Value },
	{ ContextMgmt_param_data_l1_rcr7_pixe_mask, E_PARAM_ID_PIXEL_MASK_L1R6, Value },
	{ ContextMgmt_param_data_l1_rcr8_pixe_mask, E_PARAM_ID_PIXEL_MASK_L1R7, Value },
	{ ContextMgmt_param_data_l2_rcr1_pixe_mask1, E_PARAM_ID_PIXEL_MASK_L2R0P1, Value },
	{ ContextMgmt_param_data_l2_rcr1_pixe_mask2, E_PARAM_ID_PIXEL_MASK_L2R0P2, Value },
	{ ContextMgmt_param_data_l2_rcr1_pixe_mask3, E_PARAM_ID_PIXEL_MASK_L2R0P3, Value },
	{ ContextMgmt_param_data_l2_rcr1_pixe_mask4, E_PARAM_ID_PIXEL_MASK_L2R0P4, Value },
	{ ContextMgmt_param_data_l2_rcr1_pixe_mask5, E_PARAM_ID_PIXEL_MASK_L2R0P5, Value },
	{ ContextMgmt_param_data_l2_rcr2_pixe_mask1, E_PARAM_ID_PIXEL_MASK_L2R1P1, Value },
	{ ContextMgmt_param_data_l2_rcr2_pixe_mask2, E_PARAM_ID_PIXEL_MASK_L2R1P2, Value },
	{ ContextMgmt_param_data_l2_rcr2_pixe_mask3, E_PARAM_ID_PIXEL_MASK_L2R1P3, Value },
	{ ContextMgmt_param_data_l2_rcr2_pixe_mask4, E_PARAM_ID_PIXEL_MASK_L2R1P4, Value },
	{ ContextMgmt_param_data_l2_rcr2_pixe_mask5, E_PARAM_ID_PIXEL_MASK_L2R1P5, Value },
	{ ContextMgmt_param_data_l2_rcr3_pixe_mask1, E_PARAM_ID_PIXEL_MASK_L2R2P1, Value },
	{ ContextMgmt_param_data_l2_rcr3_pixe_mask2, E_PARAM_ID_PIXEL_MASK_L2R2P2, Value },
	{ ContextMgmt_param_data_l2_rcr3_pixe_mask3, E_PARAM_ID_PIXEL_MASK_L2R2P3, Value },
	{ ContextMgmt_param_data_l2_rcr3_pixe_mask4, E_PARAM_ID_PIXEL_MASK_L2R2P4, Value },
	{ ContextMgmt_param_data_l2_rcr3_pixe_mask5, E_PARAM_ID_PIXEL_MASK_L2R2P5, Value },
	{ ContextMgmt_param_data_l2_rcr4_pixe_mask1, E_PARAM_ID_PIXEL_MASK_L2R3P1, Value },
	{ ContextMgmt_param_data_l2_rcr4_pixe_mask2, E_PARAM_ID_PIXEL_MASK_L2R3P2, Value },
	{ ContextMgmt_param_data_l2_rcr4_pixe_mask3, E_PARAM_ID_PIXEL_MASK_L2R3P3, Value },
	{ ContextMgmt_param_data_l2_rcr4_pixe_mask4, E_PARAM_ID_PIXEL_MASK_L2R3P4, Value },
	{ ContextMgmt_param_data_l2_rcr4_pixe_mask5, E_PARAM_ID_PIXEL_MASK_L2R3P5, Value },
	{ ContextMgmt_param_data_l2_rcr5_pixe_mask1, E_PARAM_ID_PIXEL_MASK_L2R4P1, Value },
	{ ContextMgmt_param_data_l2_rcr5_pixe_mask2, E_PARAM_ID_PIXEL_MASK_L2R4P2, Value },
	{ ContextMgmt_param_data_l2_rcr5_pixe_mask3, E_PARAM_ID_PIXEL_MASK_L2R4P3, Value },
	{ ContextMgmt_param_data_l2_rcr5_pixe_mask4, E_PARAM_ID_PIXEL_MASK_L2R4P4, Value },
	{ ContextMgmt_param_data_l2_rcr5_pixe_mask5, E_PARAM_ID_PIXEL_MASK_L2R4P5, Value },
	{ ContextMgmt_param_data_l2_rcr6_pixe_mask1, E_PARAM_ID_PIXEL_MASK_L2R5P1, Value },
	{ ContextMgmt_param_data_l2_rcr6_pixe_mask2, E_PARAM_ID_PIXEL_MASK_L2R5P2, Value },
	{ ContextMgmt_param_data_l2_rcr6_pixe_mask3, E_PARAM_ID_PIXEL_MASK_L2R5P3, Value },
	{ ContextMgmt_param_data_l2_rcr6_pixe_mask4, E_PARAM_ID_PIXEL_MASK_L2R5P4, Value },
	{ ContextMgmt_param_data_l2_rcr6_pixe_mask5, E_PARAM_ID_PIXEL_MASK_L2R5P5, Value },
	{ ContextMgmt_param_data_l2_rcr7_pixe_mask1, E_PARAM_ID_PIXEL_MASK_L2R6P1, Value },
	{ ContextMgmt_param_data_l2_rcr7_pixe_mask2, E_PARAM_ID_PIXEL_MASK_L2R6P2, Value },
	{ ContextMgmt_param_data_l2_rcr7_pixe_mask3, E_PARAM_ID_PIXEL_MASK_L2R6P3, Value },
	{ ContextMgmt_param_data_l2_rcr7_pixe_mask4, E_PARAM_ID_PIXEL_MASK_L2R6P4, Value },
	{ ContextMgmt_param_data_l2_rcr7_pixe_mask5, E_PARAM_ID_PIXEL_MASK_L2R6P5, Value },
	{ ContextMgmt_param_data_l2_rcr8_pixe_mask1, E_PARAM_ID_PIXEL_MASK_L2R7P1, Value },
	{ ContextMgmt_param_data_l2_rcr8_pixe_mask2, E_PARAM_ID_PIXEL_MASK_L2R7P2, Value },
	{ ContextMgmt_param_data_l2_rcr8_pixe_mask3, E_PARAM_ID_PIXEL_MASK_L2R7P3, Value },
	{ ContextMgmt_param_data_l2_rcr8_pixe_mask4, E_PARAM_ID_PIXEL_MASK_L2R7P4, Value },
	{ ContextMgmt_param_data_l2_rcr8_pixe_mask5, E_PARAM_ID_PIXEL_MASK_L2R7P5, Value },
	{ ContextMgmt_param_data_l3_rcr1_pixe_mask1, E_PARAM_ID_PIXEL_MASK_L3R0P1, Value },
	{ ContextMgmt_param_data_l3_rcr1_pixe_mask2, E_PARAM_ID_PIXEL_MASK_L3R0P2, Value },
	{ ContextMgmt_param_data_l3_rcr1_pixe_mask3, E_PARAM_ID_PIXEL_MASK_L3R0P3, Value },
	{ ContextMgmt_param_data_l3_rcr1_pixe_mask4, E_PARAM_ID_PIXEL_MASK_L3R0P4, Value },
	{ ContextMgmt_param_data_l3_rcr1_pixe_mask5, E_PARAM_ID_PIXEL_MASK_L3R0P5, Value },
	{ ContextMgmt_param_data_l3_rcr2_pixe_mask1, E_PARAM_ID_PIXEL_MASK_L3R1P1, Value },
	{ ContextMgmt_param_data_l3_rcr2_pixe_mask2, E_PARAM_ID_PIXEL_MASK_L3R1P2, Value },
	{ ContextMgmt_param_data_l3_rcr2_pixe_mask3, E_PARAM_ID_PIXEL_MASK_L3R1P3, Value },
	{ ContextMgmt_param_data_l3_rcr2_pixe_mask4, E_PARAM_ID_PIXEL_MASK_L3R1P4, Value },
	{ ContextMgmt_param_data_l3_rcr2_pixe_mask5, E_PARAM_ID_PIXEL_MASK_L3R1P5, Value },
	{ ContextMgmt_param_data_l3_rcr3_pixe_mask1, E_PARAM_ID_PIXEL_MASK_L3R2P1, Value },
	{ ContextMgmt_param_data_l3_rcr3_pixe_mask2, E_PARAM_ID_PIXEL_MASK_L3R2P2, Value },
	{ ContextMgmt_param_data_l3_rcr3_pixe_mask3, E_PARAM_ID_PIXEL_MASK_L3R2P3, Value },
	{ ContextMgmt_param_data_l3_rcr3_pixe_mask4, E_PARAM_ID_PIXEL_MASK_L3R2P4, Value },
	{ ContextMgmt_param_data_l3_rcr3_pixe_mask5, E_PARAM_ID_PIXEL_MASK_L3R2P5, Value },
	{ ContextMgmt_param_data_l3_rcr4_pixe_mask1, E_PARAM_ID_PIXEL_MASK_L3R3P1, Value },
	{ ContextMgmt_param_data_l3_rcr4_pixe_mask2, E_PARAM_ID_PIXEL_MASK_L3R3P2, Value },
	{ ContextMgmt_param_data_l3_rcr4_pixe_mask3, E_PARAM_ID_PIXEL_MASK_L3R3P3, Value },
	{ ContextMgmt_param_data_l3_rcr4_pixe_mask4, E_PARAM_ID_PIXEL_MASK_L3R3P4, Value },
	{ ContextMgmt_param_data_l3_rcr4_pixe_mask5, E_PARAM_ID_PIXEL_MASK_L3R3P5, Value },
	{ ContextMgmt_param_data_l3_rcr5_pixe_mask1, E_PARAM_ID_PIXEL_MASK_L3R4P1, Value },
	{ ContextMgmt_param_data_l3_rcr5_pixe_mask2, E_PARAM_ID_PIXEL_MASK_L3R4P2, Value },
	{ ContextMgmt_param_data_l3_rcr5_pixe_mask3, E_PARAM_ID_PIXEL_MASK_L3R4P3, Value },
	{ ContextMgmt_param_data_l3_rcr5_pixe_mask4, E_PARAM_ID_PIXEL_MASK_L3R4P4, Value },
	{ ContextMgmt_param_data_l3_rcr5_pixe_mask5, E_PARAM_ID_PIXEL_MASK_L3R4P5, Value },
	{ ContextMgmt_param_data_l3_rcr6_pixe_mask1, E_PARAM_ID_PIXEL_MASK_L3R5P1, Value },
	{ ContextMgmt_param_data_l3_rcr6_pixe_mask2, E_PARAM_ID_PIXEL_MASK_L3R5P2, Value },
	{ ContextMgmt_param_data_l3_rcr6_pixe_mask3, E_PARAM_ID_PIXEL_MASK_L3R5P3, Value },
	{ ContextMgmt_param_data_l3_rcr6_pixe_mask4, E_PARAM_ID_PIXEL_MASK_L3R5P4, Value },
	{ ContextMgmt_param_data_l3_rcr6_pixe_mask5, E_PARAM_ID_PIXEL_MASK_L3R5P5, Value },
	{ ContextMgmt_param_data_l3_rcr7_pixe_mask1, E_PARAM_ID_PIXEL_MASK_L3R6P1, Value },
	{ ContextMgmt_param_data_l3_rcr7_pixe_mask2, E_PARAM_ID_PIXEL_MASK_L3R6P2, Value },
	{ ContextMgmt_param_data_l3_rcr7_pixe_mask3, E_PARAM_ID_PIXEL_MASK_L3R6P3, Value },
	{ ContextMgmt_param_data_l3_rcr7_pixe_mask4, E_PARAM_ID_PIXEL_MASK_L3R6P4, Value },
	{ ContextMgmt_param_data_l3_rcr7_pixe_mask5, E_PARAM_ID_PIXEL_MASK_L3R6P5, Value },
	{ ContextMgmt_param_data_l3_rcr8_pixe_mask1, E_PARAM_ID_PIXEL_MASK_L3R7P1, Value },
	{ ContextMgmt_param_data_l3_rcr8_pixe_mask2, E_PARAM_ID_PIXEL_MASK_L3R7P2, Value },
	{ ContextMgmt_param_data_l3_rcr8_pixe_mask3, E_PARAM_ID_PIXEL_MASK_L3R7P3, Value },
	{ ContextMgmt_param_data_l3_rcr8_pixe_mask4, E_PARAM_ID_PIXEL_MASK_L3R7P4, Value },
	{ ContextMgmt_param_data_l3_rcr8_pixe_mask5, E_PARAM_ID_PIXEL_MASK_L3R7P5, Value },
	{ ContextMgmt_param_data_enable_bckg_dete_formatting, E_PARAM_ID_INCLUDE_BCKG, Value },
	{ ContextMgmt_param_data_enable_cfl_dete_formatting, E_PARAM_ID_INCLUDE_CFL, Value },
	{ ContextMgmt_param_imaging_dete_mask, E_PARAM_ID_IMAGING_DETE_MASK, Value },
	{ ContextMgmt_param_imaging_trim_N, E_PARAM_ID_IMAGING_TRIM_N, Value },
	{ ContextMgmt_param_imaging_trim_F, E_PARAM_ID_IMAGING_TRIM_F, Value },
	{ ContextMgmt_param_imaging_bckg_determination, E_PARAM_ID_IMAGING_BCKG_DETERMIN, Value },
	{ ContextMgmt_param_spectro_dete_mask, E_PARAM_ID_SPECTRO_DETE_MASK, Value },
	{ ContextMgmt_param_spectro_pixe_mask, E_PARAM_ID_SPECTRO_PIXE_MASK, Value },
	{ ContextMgmt_param_spectro_bckg_determination, E_PARAM_ID_SPECTRO_BCKG_DETERMIN, Value },
	{ ContextMgmt_param_hk_period_sid2, E_PARAM_ID_HK_TM_SID2_REPORTING_PERIOD, Value },
	{ ContextMgmt_param_hk_period_sid4, E_PARAM_ID_HK_TM_SID4_REPORTING_PERIOD, Value },
	{ ContextMgmt_param_enabled_science_data_transfer, E_PARAM_ID_ENABLED_SSID_TRANSFFER_TO_SSMM_MASK, Value },
	{ ContextMgmt_param_elut_lut, E_PARAM_ID_CONFIG_CURRENT_ELUT_ID, Value },
	{ ContextMgmt_param_tlut1_lut, E_PARAM_ID_CONFIG_CURRENT_TLUT1_ID, Value },
	{ ContextMgmt_param_tlut2_lut, E_PARAM_ID_CONFIG_CURRENT_TLUT2_ID, Value },
	{ ContextMgmt_param_tlut_dete_quarter_mask, E_PARAM_ID_CONFIG_TLUT_ENABLED_DET_TEMP_MASK, Value },
	{ ContextMgmt_param_tlut_number_of_temperatures_for_average, E_PARAM_ID_CONFIG_TLUT_AVG_READOUT_COUNT, Value },
	{ ContextMgmt_param_compression_l1l2_counts, E_PARAM_ID_COMPRESSION_SCHEME_L1L2_COUNTS, Value },
	{ ContextMgmt_param_compression_l1l2l3_triggers, E_PARAM_ID_COMPRESSION_SCHEME_L1L2L3L4_TRIGGERS, Value },
	{ ContextMgmt_param_compression_l3_counts, E_PARAM_ID_COMPRESSION_SCHEME_L3_VISIBILITY, Value },
	{ ContextMgmt_param_compression_spectro_counts, E_PARAM_ID_COMPRESSION_SCHEME_SPECTROGRAM_COUNTS, Value },
	{ ContextMgmt_param_tmmgmt_publishing_interval, E_PARAM_ID_TM_MGMT_PUBLISHING_INTERVAL, Value },
	{ ContextMgmt_param_tmmgmt_corridor_t1, E_PARAM_ID_TM_MGMT_T1, Value },
	{ ContextMgmt_param_tmmgmt_corridor_t2, E_PARAM_ID_TM_MGMT_T2, Value },
	{ ContextMgmt_param_tmmgmt_corridor_m1, E_PARAM_ID_TM_MGMT_M1, Value },
	{ ContextMgmt_param_tmmgmt_corridor_m2, E_PARAM_ID_TM_MGMT_M2, Value },
	{ ContextMgmt_param_aspect_halves_power, E_PARAM_ID_ASPECT_HALVES_POWER, Value },
	{ ContextMgmt_param_att_openned_motor, E_PARAM_ID_ATT_OPENNED_MOTOR, Value },
	{ ContextMgmt_param_calib_compression_schema, E_PARAM_ID_CALIB_COMPRESSION_SCHEMA, Value },
	{ ContextMgmt_param_calib_formatting_enabled, E_PARAM_ID_CALIB_FORMATTING_ENABLED, Value },
	{ ContextMgmt_param_calib_pixel_mask, E_PARAM_ID_CALIB_PIXEL_MASK, Value },
	{ ContextMgmt_param_config_adc_enable_mask, E_PARAM_ID_CONFIG_ADC_ENABLE_MASK, Value },
	{ ContextMgmt_param_config_adc_mode_mask, E_PARAM_ID_CONFIG_ADC_MODE_MASK, Value },
	{ ContextMgmt_param_config_enabled_edac, E_PARAM_ID_CONFIG_ENABLED_EDAC, Value },
	{ ContextMgmt_param_config_scrub_cache, E_PARAM_ID_CONFIG_SCRUB_CACHE, Value },
	{ ContextMgmt_param_config_scrub_sdram, E_PARAM_ID_CONFIG_SCRUB_SDRAM, Value },
	{ ContextMgmt_param_config_spw_state, E_PARAM_ID_CONFIG_SPW_STATE, Value },
	{ ContextMgmt_param_detector_mask_l1, E_PARAM_ID_DETECTOR_MASK_L1, Value },
	{ ContextMgmt_param_detector_mask_l2, E_PARAM_ID_DETECTOR_MASK_L2, Value },
	{ ContextMgmt_param_detector_mask_l3, E_PARAM_ID_DETECTOR_MASK_L3, Value },
	{ ContextMgmt_param_detector_mask_l4, E_PARAM_ID_DETECTOR_MASK_L4, Value },
	{ ContextMgmt_param_edac_scrub_algo_cache_threshold_high, E_PARAM_ID_EDAC_SCRUB_ALGO_CACHE_THRESHOLD_HIGH, Value },
	{ ContextMgmt_param_edac_scrub_algo_cache_threshold_nom, E_PARAM_ID_EDAC_SCRUB_ALGO_CACHE_THRESHOLD_NOM, Value },
	{ ContextMgmt_param_edac_scrub_algo_sdram_threshold_high, E_PARAM_ID_EDAC_SCRUB_ALGO_SDRAM_THRESHOLD_HIGH, Value },
	{ ContextMgmt_param_edac_scrub_algo_sdram_threshold_nom, E_PARAM_ID_EDAC_SCRUB_ALGO_SDRAM_THRESHOLD_NOM, Value },
	{ ContextMgmt_param_edac_seu_report_period_s, E_PARAM_ID_EDAC_SEU_REPORT_PERIOD_S, Value },
	{ ContextMgmt_param_fdir_irq_counter_max_dataflash, E_PARAM_ID_FDIR_IRQ_COUNTER_MAX_DATAFLASH, Value },
	{ ContextMgmt_param_fdir_irq_counter_max_detector, E_PARAM_ID_FDIR_IRQ_COUNTER_MAX_DETECTOR, Value },
	{ ContextMgmt_param_fdir_irq_counter_max_detector_ql, E_PARAM_ID_FDIR_IRQ_COUNTER_MAX_DETECTOR_QL, Value },
	{ ContextMgmt_param_fdir_irq_counter_max_spw, E_PARAM_ID_FDIR_IRQ_COUNTER_MAX_SPW, Value },
	{ ContextMgmt_param_flare_list_last_report_scet, E_PARAM_ID_FLARE_LIST_LAST_REPORT_SCET, Value },
	{ ContextMgmt_param_hk_tm_sid2_reporting_enabled, E_PARAM_ID_HK_TM_SID2_REPORTING_ENABLED, Value },
	{ ContextMgmt_param_hk_tm_sid4_reporting_enabled, E_PARAM_ID_HK_TM_SID4_REPORTING_ENABLED, Value },
	{ ContextMgmt_param_hv_reset_delay_from_flare, E_PARAM_ID_HV_RESET_DELAY_FROM_FLARE, Value },
	{ ContextMgmt_param_lv_state, E_PARAM_ID_LV_State, Value },
	{ ContextMgmt_param_mem_load_enabled, E_PARAM_ID_MEM_LOAD_ENABLED, Value },
	{ ContextMgmt_param_fdir_sw_psut_min, E_PARAM_ID_PSU_TEMP, Min },
	{ ContextMgmt_param_ql_flaredet_dete_mask, E_PARAM_ID_QL_FLAREDET_DETE_MASK, Value },
	{ ContextMgmt_param_ql_spectrum_number_of_wait_iterations, E_PARAM_ID_QL_SPECTRUM_NUMBER_OF_WAIT_ITERATIONS, Value },
	{ ContextMgmt_param_rcr_b0, E_PARAM_ID_RCR_B0, Value },
	{ ContextMgmt_param_spw_time_code_reception_timeout_ms, E_PARAM_ID_SPW_TIME_CODE_RECEPTION_TIMEOUT_MS, Value },
	{ ContextMgmt_param_fdir_sw_psut_max, E_PARAM_ID_PSU_TEMP, Max },
	{ ContextMgmt_param_flare_sel_period, E_PARAM_ID_FLARE_SEL_PERIOD, Value },
	{ ContextMgmt_param_flare_sel_latency, E_PARAM_ID_FLARE_SEL_LATENCY, Value },
	{ ContextMgmt_param_flare_sel_enabled, E_PARAM_ID_FLARE_SEL_ENABLED, Value },
	{ ContextMgmt_param_flare_sel_start, E_PARAM_ID_FLARE_SEL_START, Value },
	{ ContextMgmt_param_flare_sel_stop, E_PARAM_ID_FLARE_SEL_STOP, Value },
	{ ContextMgmt_param_fs_rewrite_files_after_n_seus, E_PARAM_ID_FS_REWRITE_FILES_AFTER_N_SEUS, Value },
	{ ContextMgmt_params_att_global_disable_flag, E_PARAM_ID_ATT_GLOBAL_DISABLE_FLAG, Value },
};

//if the number of parameters, etc. changes, you might want to switch to a new CONTEXT_VERISION
//we should also check the CONTEXT_LENGTH
STATIC_ASSERT(LENGTH(ContextMgmt_c2ptable) == 487);
STATIC_ASSERT(ContextMgmt_param_last == 519);
STATIC_ASSERT(LENGTH(ContextMgmt_paramBitSize) == 519);
//sum of ContextMgmt_paramBitSize == CONTEXT_LENGTH, rounded up to the next byte

#define MAX_DATA_SIZE             ((TCDATA_MAX_PACKET_LENGTH) - 12 - 2) //236 - 2
#define MAX_CONTEXT_SEGMENT       (((CONTEXT_LENGTH) + (MAX_DATA_SIZE) - 1)/(MAX_DATA_SIZE))

#define CONTEXT_FIRST_SEGMENT                   1
#define CONTEST_LAST_SEGMENT                    MAX_CONTEXT_SEGMENT


typedef struct contextmgmt_table_struct
{
	uint16_t                bitOffset;
	uint16_t                bitSize;
} contextmgmt_table_s;

typedef struct context_local_struct
{
	volatile bool_t fsOperationStatus;
	uint16_t  initContextCrc;
	uint32_t tc22_3_contextSegmentMask;
} contextLocal_s;

// ----------------------------------- static variables ----------------------------------------
static uint8_t contextDataLive[CONTEXT_LENGTH];
static contextLocal_s contextLocalLive_so;
static contextmgmt_table_s contextTableLive[(uint16_t)ContextMgmt_param_last];

// contextDataBackup is used when re-entering the CONFIGURATION mode to ensure we have a clean start
// Calling the ContextMgmt_init() again inside OpModeMgmt leads to stack blown!
static uint8_t contextDataBackup[CONTEXT_LENGTH];
static contextLocal_s contextLocalBackup_so;
static contextmgmt_table_s contextTableBackup[(uint16_t)ContextMgmt_param_last];

// ------------------------------------ static functions ---------------------------------------
static void context_createContextFromParameters(void);
static void context_createParametersFromContext(void);
static void get_from_context(uint8_t *arr, uint32_t offset, uint32_t size);
static void set_to_context(uint8_t *arr, uint32_t offset, uint32_t size);
static void store_new_context(void);
void PARAM2CONTEXT(ContextMgmt_param_id_e idx, ParamMgmt_param_id_e param_idx, ContextMgmt_param_part_e param_sidx);
void CONTEXT2PARAM(ContextMgmt_param_id_e idx, ParamMgmt_param_id_e param_idx, ContextMgmt_param_part_e param_sidx);
static void ContextMgmt_saveLiveToBackupContext(void);
//-----------------------------------------------------------------------------------------------

/**
 * @brief Function called when received TC(22,1) send context to OBMM
 *
 * @param destinationId destination of TM packet containing context
 *
 * @return status of generating TM packet
 */
fsw_ret_e ContextMgmt_sendContext(uint8_t destinationId)
{
	TRACE("Sending context TM with size of %u to destination  %u", CONTEXT_LENGTH, destinationId);
	return TMForm_createTM_22_2(contextDataLive, (uint16_t)CONTEXT_LENGTH, destinationId);
}

/**
 * @brief Function called when received TC(22,3) accept context segment from OBMM
 *
 * @param in_tcRawData raw data of the packet received as TC(22,3)
 * @return FSW_OK on success
 *         FSW_ERROR when context segment exceeds max segment number
 */
fsw_ret_e ContextMgmt_acceptContext(uint8_t* in_tcRawData)
{
	uint32_t contextSegment = GET16(&in_tcRawData[TCDATA_22_3_CONTEXT_SEGMENT_POS]);
	if ((contextSegment > MAX_CONTEXT_SEGMENT) || (contextSegment == 0))
	{
		TRACE_ERROR("Wrong context segment number");
		return FSW_ERROR;
	}

	// if first segment erase context segment mask
	if (contextSegment == CONTEXT_FIRST_SEGMENT)
	{
		contextLocalLive_so.tc22_3_contextSegmentMask = 1;
	}
	else
	{
		contextLocalLive_so.tc22_3_contextSegmentMask |= utils_ele2mask(contextSegment - 1);
	}


	//packet length is DATA header + CRC + APP DATA -1 :: 4 + 2 + APPDATA -1 = 5 + APPDATA
	//2B are for segment
	uint16_t appDataSize = (uint16_t)(GET16(&in_tcRawData[4]) - 5 - 2);

	if ((appDataSize + (contextSegment - 1) * MAX_DATA_SIZE) > CONTEXT_LENGTH)
	{
		TRACE_ERROR("data in context segment are too large");
		return FSW_ERROR;
	}

	memcpy(&contextDataLive[(contextSegment - 1) * MAX_DATA_SIZE], &in_tcRawData[TCDATA_22_3_CONTEXT_DATA_POS], appDataSize);

	// in case of last segmnent
	if (contextSegment == CONTEST_LAST_SEGMENT)
	{
		// check if all segments have been received
		if (contextLocalLive_so.tc22_3_contextSegmentMask == (utils_ele2mask(contextSegment) - 1))
		{
			// full context accepted
			uint16_t newCrc = Common_crc16(contextDataLive, CONTEXT_LENGTH, 0xffff);

			// compare ECC
			if (newCrc != contextLocalLive_so.initContextCrc)
			{
				// new and old context are different

			   // update parameters according to context
				context_createParametersFromContext();

				// store new ECC array
				contextLocalLive_so.initContextCrc = newCrc;

				store_new_context();
			}

			// otherwise contexts are identical
		}
		else
		{
			// when processing LAST segment, we are missing 1 or more previous segments
			TMForm_missingContextSegment(contextLocalLive_so.tc22_3_contextSegmentMask, (utils_ele2mask(contextSegment) - 1));
		}
	}

	return FSW_OK;
}

static void ContextMgmt_saveLiveToBackupContext(void)
{
	TRACE("Saving live parameter table to backup");
	memcpy(&contextDataBackup[0], &contextDataLive[0], CONTEXT_LENGTH);

	contextLocalBackup_so = contextLocalLive_so;

	memcpy(contextTableBackup, contextTableLive, sizeof(contextTableLive));
}

void ContextMgmt_resetBackupToLiveContext(void)
{
	TRACE("Resetting live parameter table with backup");
	memcpy(&contextDataLive[0], &contextDataBackup[0], CONTEXT_LENGTH);

	contextLocalLive_so = contextLocalBackup_so;

	memcpy(contextTableLive, contextTableBackup, sizeof(contextTableBackup));

	context_createParametersFromContext();
}

bool_t foundPreInitContext0 = FALSE;
bool_t foundPreInitContext1 = FALSE;
bool_t preInitRun = FALSE;

void ContextMgmt_readOnlyPreInit(void)
{
	TRACE("Context RO PRE init for VERSION %u", CONTEXT_VERSION);

	// zero context
	memset(&contextDataLive[0], 0, CONTEXT_LENGTH);

	// table initialisation
	contextTableLive[0].bitOffset = 0;
	contextTableLive[0].bitSize = ContextMgmt_paramBitSize[0];

	for (uint32_t i = 1; i < LENGTH(contextTableLive); i++)
	{
		contextTableLive[i].bitOffset = contextTableLive[i - 1].bitOffset + contextTableLive[i - 1].bitSize;
		contextTableLive[i].bitSize = ContextMgmt_paramBitSize[i];
	}

	TRACE("Context size: %u", contextTableLive[(uint32_t)ContextMgmt_param_last - 1].bitSize + contextTableLive[(uint32_t)ContextMgmt_param_last - 1].bitOffset);

	FSreadInitialContextFileViaSidechannel(&contextDataLive[0], &foundPreInitContext0, &foundPreInitContext1);

	if (foundPreInitContext0 || foundPreInitContext1)
	{
		TRACE("Found initial context for setup (CTX0: %u, CTX1: %u). Making context active!", foundPreInitContext0, foundPreInitContext1);

		// Calculate ECC to find out later if context was changed
		contextLocalLive_so.initContextCrc = Common_crc16(contextDataLive, CONTEXT_LENGTH, 0xffff);

		TRACE("Calculated the following CRC for PRE init context: %X", contextLocalLive_so.initContextCrc);

		// overwrite parameters with context
		context_createParametersFromContext();
	}
	else
	{
		TRACE("Did not find initial context. Leaving default parameters active and recreating context from defaults.");

		// prepare a context from the default parameters
		// *** DO NOT STORE THE CONTEXT TO FLASH! ***
		context_createContextFromParameters();
		contextLocalLive_so.initContextCrc = Common_crc16(contextDataLive, CONTEXT_LENGTH, 0xffff);
	}

	// in any case, save live context to backup
	ContextMgmt_saveLiveToBackupContext();

	// just ensuring we do not erase the memory again or twice
	preInitRun = TRUE;

	TRACE("Context RO PRE init finished");
}

/**
 * @brief Function called to initialise context
 *
 * Function called to initialise context, need to wait for initialised filessytem.
 * NB: ContextMgmt_readOnlyPreInit() must be called before this init!
 */
void ContextMgmt_init(void)
{
	ASSERT(preInitRun);

	MemFilesystem_filename_s context0FileName = FScreateFilename(E_MEMFILESYSTEM_FILETYPE_CONTEXT0, 0, 0, 0xFFFF, CONTEXT_VERSION);
	MemFilesystem_filename_s context1FileName = FScreateFilename(E_MEMFILESYSTEM_FILETYPE_CONTEXT1, 0, 0, 0xFFFF, CONTEXT_VERSION);

	// we found a context during PRE init
	if (foundPreInitContext0 || foundPreInitContext1)
	{
		uint16_t preInitContextCrcModified = Common_crc16(contextDataLive, CONTEXT_LENGTH, 0xffff);

		TRACE("Calculated the following CRC for PRE init context MODIFIED: %X", preInitContextCrcModified);

		if (contextLocalLive_so.initContextCrc == preInitContextCrcModified)
		{
			TRACE("PRE init context was not modified.");

			// Check if one of the context files needs to be restored
			if (!foundPreInitContext0)
			{
				TRACE("Context 0 was missing --> store loaded context to flash.");
				fsw_ret_e error = FSwrite(&context0FileName, contextDataLive, CONTEXT_LENGTH);
				TMForm_contextFileLoadingProblem(error != FSW_OK, TRUE);
			}

			if (!foundPreInitContext1)
			{
				TRACE("Context 1 was missing --> store loaded context to flash.");
				fsw_ret_e error = FSwrite(&context1FileName, contextDataLive, CONTEXT_LENGTH);
				TMForm_contextFileLoadingProblem(TRUE, error != FSW_OK);
			}

			// no ECC update needed as nothing has changed

			// save (update) shadow copy
			ContextMgmt_saveLiveToBackupContext();
		}
		else
		{
			TRACE("PRE init context WAS modified. Need to store update.");

			// this will save both context files
			// not sending any TMs about failed context (as I do above)
			contextLocalLive_so.initContextCrc = Common_crc16(contextDataLive, CONTEXT_LENGTH, 0xffff);
			store_new_context();
		}
	}
	else
	{
		// no context files were found, need to create them from the parameters
		// not necessary to rerun context generation or ECC calculation, we did that already during PRE init
		store_new_context();
		TMForm_contextFileLoadingProblem(TRUE, TRUE);
	}
}

/**
 * @brief Function used to compare parameters with what is loaded in context (in FLASH)
 *
 * Function creates new context array that is compared to the array stored in Flash, and if they differ, new array is stored in FLASH.
 */
void ContextMgmt_deinit(void)
{
	// create new context
	context_createContextFromParameters();
	uint16_t crcArr = Common_crc16(contextDataLive, CONTEXT_LENGTH, 0xffff);

	if (crcArr != contextLocalLive_so.initContextCrc)
	{
		// context created from parameters differ from stored context - store new context
		TRACE("ECC arrays differ, store new context");
		store_new_context();
	}
}

// ------------------------------ static functions -----------------------------------------
/**
 * @brief function used to obtain bit string from context
 *
 * Function to obtain bit string from context and put it into array.
 * Output string is aligned to LSb.
 *
 * @param inout_arr byte array that requested bits are stored into
 * @param in_offset offset within context to start reading bits
 * @param in_size   size of bit-string to read
 */
static void get_from_context(uint8_t *inout_arr, uint32_t in_offset, uint32_t in_size)
{
	uint32_t inByte = in_offset / 8;    ///< first byte to read from context (0 == MSB)
	uint32_t inBit = in_offset % 8;    ///< first bit to read from context (0 == MSb)
	uint32_t outByte = 0;                ///< first byte to write to (start from 0th)
	uint32_t outBit = 8 - (in_size % 8);///< in order to have right-aligned (LSb) array, first bit to write to (0 == MSb)
	uint32_t step = 8 - inBit;           ///< step to process

	if (outBit == 8)
	{
		outBit = 0;
	}

	while (in_size)
	{
		step = (step > in_size) ? in_size : step;

		// reading from context
		uint32_t cnt = (contextDataLive[inByte] >> (8 - inBit - step)) & (utils_ele2mask(step) - 1);

		// either this is last iteration or it will be always from the start of byte (1st iteration starts according to offset)
		inBit = 0;
		inByte++;

		// filling output array
		if (outBit + step > 8)
		{
			// split
			uint32_t step1 = 8 - outBit;    // written to 1st byte
			uint32_t step2 = step - step1;  // written to 2nd byte

			inout_arr[outByte] &= ~(utils_ele2mask(step1) - 1);
			inout_arr[outByte] |= (cnt >> step2);

			inout_arr[outByte + 1] &= ~((utils_ele2mask(step2) - 1) << (8 - step2));
			inout_arr[outByte + 1] |= (cnt & (utils_ele2mask(step2) - 1)) << (8 - step2);
		}
		else
		{
			// zero are to be overwritten
			inout_arr[outByte] &= ~((utils_ele2mask(step) - 1) << (8 - step - outBit));
			// file zeroed bits with data
			inout_arr[outByte] |= (cnt << (8 - step - outBit));
		}

		outBit += step;
		if (outBit >= 8)
		{
			outBit -= 8;
			outByte++;
		}

		in_size -= step;
		step = 8;
	}
}

/**
 * @brief function used to write string to context
 *
 * Function to write bit string to context.
 * Input string is aligned to LSb, where 0-th byte of input array already contains data to write, i.e.
 * 13b string stored in 2B has from MSb of MSB 3b spare + 5b of data in MSB + 8b of data in LSB.
 *
 * @param inout_arr byte array that requested bits are stored into
 * @param in_offset offset within context to start reading bits
 * @param in_size   size of bit-string to read
 */
static void set_to_context(uint8_t *in_arr, uint32_t in_offset, uint32_t in_size)
{
	uint32_t outByte = in_offset / 8;   ///< first byte to write to
	uint32_t outBit = 7 - in_offset % 8; ///< first bit to write to (7 == MSb)
	uint32_t inByte = 0;                 ///< first byte to read
	uint32_t step = in_size % 8;           ///< reading step (from input data)
	uint32_t inBit = step - 1;            ///< first bit to read from first byte (7 == MSb)

	// if byte aligned variable
	if (step == 0)
	{
		// set step to byte
		step = 8;
		inBit = 7;
	}

	while (in_size)
	{
		step = (step > in_size) ? in_size : step;

		// reading data - extract data from given byte
		uint8_t cnt = (in_arr[inByte] >> (inBit + 1 - step)) & (utils_ele2mask(step) - 1);

		// prepare variables for extracting from next byte
		inBit = 7;
		inByte++;

		// filling in context
		if (outBit + 1 < step)
		{
			// split into 2 bytes
			uint8_t step1 = outBit + 1;      // written to 1st byte
			uint8_t step2 = step - step1;  // written to 2nd byte

			// write 1st byte (up to LSb)
			contextDataLive[outByte] &= ~(utils_ele2mask(step1) - 1);
			contextDataLive[outByte] |= ((cnt >> step2) & (utils_ele2mask(step1) - 1));

			// write 2nd byte (from MSb)
			contextDataLive[outByte + 1] &= ~((utils_ele2mask(step2) - 1) << (8 - step2));
			contextDataLive[outByte + 1] |= ((cnt & (utils_ele2mask(step2) - 1)) << (8 - step2));

			// finalise for next iteration
			outByte++;
			outBit = 8 - step2 - 1;
		}
		else
		{
			// will be filled in 1 byte
			// zero are to be overwritten
			contextDataLive[outByte] &= ~((utils_ele2mask(step) - 1) << (outBit + 1 - step));
			// file zeroed bits with data
			contextDataLive[outByte] |= (cnt << (outBit + 1 - step));

			// prepare for next writing
			if (step <= outBit)
			{
				outBit -= step;
			}
			else
			{
				outByte++;
				outBit = 7;
			}
		}

		// decrease remaining size by processed step
		in_size -= step;
		step = 8;
	}
}


void CONTEXT2PARAM(ContextMgmt_param_id_e idx, ParamMgmt_param_id_e param_idx, ContextMgmt_param_part_e param_sidx)
{
	ASSERT(contextTableLive[idx].bitSize <= 8 * sizeof(uint32_t));
	if (contextTableLive[idx].bitSize > 8 * sizeof(uint32_t))
	{
		TRACE_ERROR("parameter too big for variable:b=%u", contextTableLive[idx].bitSize);
		return;
	}

	uint32_t u32 = 0;
	get_from_context((uint8_t*)&u32, contextTableLive[idx].bitOffset, contextTableLive[idx].bitSize);

	// 8bits or less -> move from 0th to 3rd byte
	if (contextTableLive[idx].bitSize <= 8)
	{
		u32 >>= 24;
	}
	// 9-16bits -> move from 1st to 3rd byte
	else if (contextTableLive[idx].bitSize <= 16)
	{
		u32 >>= 16;
	}
	// 17-24bits -> move from 2nd to 3rd byte
	else if (contextTableLive[idx].bitSize <= 24)
	{
		u32 >>= 8;
	}
	// otherwise aligned to 4B

	fsw_ret_e retv;
	if (Value == param_sidx)
	{
		retv = ParamMgmt_setParamValue(param_idx, u32);
	}
	else if (Min == param_sidx)
	{
		retv = ParamMgmt_setParamMinValue(param_idx, u32);
	}
	else if (Max == param_sidx)
	{
		retv = ParamMgmt_setParamMaxValue(param_idx, u32);
	}
	else
	{
		TRACE_ERROR("Incorrect param_sidx %u", param_sidx);
		ASSERT(0);
		retv = 0;
	}

	if (FSW_OK != retv)
	{
		TRACE_ERROR("incorrect retval %u for paramId=%u contextId=%u paramOp=%u lower=%u, value=%u, upper=%u, ctxval=%u", retv, param_idx, idx, param_sidx,
			ParamMgmt_getParamMinValue(param_idx),
			ParamMgmt_getParamValue(param_idx),
			ParamMgmt_getParamMaxValue(param_idx),
			u32);
	}
}

void PARAM2CONTEXT(ContextMgmt_param_id_e idx, ParamMgmt_param_id_e param_idx, ContextMgmt_param_part_e param_sidx)
{
	if (contextTableLive[idx].bitSize > 8 * sizeof(uint32_t))
	{
		TRACE_ERROR("parameter too big for variable:b=%u", contextTableLive[idx].bitSize);
		return;
	}

	uint32_t u32;
	if (Value == param_sidx)
	{
		u32 = ParamMgmt_getParamValue(param_idx);
	}
	else if (Min == param_sidx)
	{
		u32 = ParamMgmt_getParamMinValue(param_idx);
	}
	else if (Max == param_sidx)
	{
		u32 = ParamMgmt_getParamMaxValue(param_idx);
	}

	if (contextTableLive[idx].bitSize <= 8)
	{
		u32 <<= 24;
	}
	else if (contextTableLive[idx].bitSize <= 16)
	{
		u32 <<= 16;
	}
	else if (contextTableLive[idx].bitSize <= 24)
	{
		u32 <<= 8;
	}

	set_to_context((uint8_t*)&u32, contextTableLive[idx].bitOffset, contextTableLive[idx].bitSize);
}

static void context_createParametersFromContext(void)
{
	for (uint32_t i = 0; i < LENGTH(ContextMgmt_c2ptable); i++)
		CONTEXT2PARAM(ContextMgmt_c2ptable[i].ctx, ContextMgmt_c2ptable[i].param, ContextMgmt_c2ptable[i].part);

	for (uint32_t iDet = 0; iDet < NUMBER_OF_DETECTORS; iDet++)
	{
		commonFSW_deteReg_s* defaultReg = XRayADCsCtrl_getDefaultRegisters(iDet);

		for (uint32_t iReg = 0; iReg < ASIC_NUMBER_OF_REGISTERS; iReg++)
		{
			// offset due to individual registers
			uint32_t contextOffset = context_register_bit_offset[iReg] + contextTableLive[(uint16_t)ContextMgmt_param_xray01_registers + iDet].bitOffset;

			// size of individual registers
			uint32_t contextRegSize;
			uint32_t pixelCount;
			if ((iReg + 1 == ASIC_REGISTER_3) || (iReg + 1 == ASIC_REGISTER_4) || (iReg + 1 == ASIC_REGISTER_12))
			{
				pixelCount = NUMBER_OF_PIXELS;
				contextRegSize = context_register_bit_size[iReg] / NUMBER_OF_PIXELS;
			}
			else
			{
				pixelCount = 1;
				contextRegSize = context_register_bit_size[iReg];
			}

			// loop over all pixels
			for (uint32_t iPixel = 0; iPixel < pixelCount; iPixel++)
			{
				uint8_t regByte = 0;
				get_from_context(&regByte, contextOffset, contextRegSize);

				if (regByte > 63)
				{
					TRACE_ERROR("incorrect register value: 0x%02x for det %u and register %u", regByte, iDet, iReg);
					ASSERT(0);
					regByte = 63;
				}

				switch (iReg + 1)
				{
				case ASIC_REGISTER_3:
					utils_setReg3(utils_pixelId2channelId[iPixel], regByte, defaultReg->reg03);
					break;
				case ASIC_REGISTER_4:
				case ASIC_REGISTER_12:
					// bit corresponding pixel is already zeroed
					// regByte should have 1bit (T/F) to affect filling in the registers
					defaultReg->ptrs[iReg][3 - (utils_pixelId2channelId[iPixel] / 8)] |= (1u << (utils_pixelId2channelId[iPixel] % 8)) * regByte;
					break;
				default:
					*(defaultReg->ptrs[iReg]) = regByte;
					break;
				}

				contextOffset += contextRegSize;
			}
		}
	}
}

static void context_createContextFromParameters(void)
{
	for (uint32_t i = 0; i < LENGTH(ContextMgmt_c2ptable); i++)
		PARAM2CONTEXT(ContextMgmt_c2ptable[i].ctx, ContextMgmt_c2ptable[i].param, ContextMgmt_c2ptable[i].part);

	for (uint32_t iDet = 0; iDet < NUMBER_OF_DETECTORS; iDet++)
	{
		commonFSW_deteReg_s* defaultReg = XRayADCsCtrl_getDefaultRegisters(iDet);

		for (uint32_t iReg = 0; iReg < ASIC_NUMBER_OF_REGISTERS; iReg++)
		{
			// offset due to individual registers
			uint32_t contextOffset = context_register_bit_offset[iReg] + contextTableLive[(uint16_t)ContextMgmt_param_xray01_registers + iDet].bitOffset;

			// size of individual registers
			uint32_t contextRegSize;
			uint32_t pixelCount;
			if ((iReg + 1 == ASIC_REGISTER_3) || (iReg + 1 == ASIC_REGISTER_4) || (iReg + 1 == ASIC_REGISTER_12))
			{
				pixelCount = NUMBER_OF_PIXELS;
				contextRegSize = context_register_bit_size[iReg] / NUMBER_OF_PIXELS;
			}
			else
			{
				pixelCount = 1;
				contextRegSize = context_register_bit_size[iReg];
			}

			// loop over all pixels
			for (uint32_t iPixel = 0; iPixel < pixelCount; iPixel++)
			{
				uint8_t regByte = 0;
				switch (iReg + 1)
				{
				case ASIC_REGISTER_3:
					regByte = utils_getReg3(utils_pixelId2channelId[iPixel], defaultReg->reg03);
					break;
				case ASIC_REGISTER_4:
				case ASIC_REGISTER_12:
					// bit corresponding pixel is already zeroed
					regByte = 0x1 & (defaultReg->ptrs[iReg][3 - (utils_pixelId2channelId[iPixel] / 8)] >> (utils_pixelId2channelId[iPixel] % 8));
					break;
				default:
					regByte = *(defaultReg->ptrs[iReg]);
					break;
				}

				set_to_context(&regByte, contextOffset, contextRegSize);

				contextOffset += contextRegSize;
			}
		}
	}
}

/**
 * @brief Function stores 2 new context files
 *
 * Function looks if original context exist and erases them, replacing by new contexts
 */
void store_new_context(void)
{
	MemFilesystem_filename_s filename = FScreateFilename(E_MEMFILESYSTEM_FILETYPE_CONTEXT0, 0, 0, 0xFFFF, CONTEXT_VERSION);
	(void)FSdelete(&filename);
	fsw_ret_e e = FSwrite(&filename, &contextDataLive[0], CONTEXT_LENGTH);
	if (e != FSW_OK)
	{
		TRACE_ERROR("storing new context0 failed: err code %u", e);
	}

	filename.filenameArray[FILENAME_BYTE_TYPE_ID] = E_MEMFILESYSTEM_FILETYPE_CONTEXT1;
	(void)FSdelete(&filename);
	e = FSwrite(&filename, &contextDataLive[0], CONTEXT_LENGTH);
	if (e != FSW_OK)
	{
		TRACE_ERROR("storing new context1 failed: err code %u", e);
	}

	ContextMgmt_saveLiveToBackupContext();

	TRACE("context writing DONE for VERSION %u", CONTEXT_VERSION);
}
//
