# a script used to generate a list of differencess between OBT and UNIX epochs 
# the list is used by web data browsers and Starlet

from stix.core import stix_datetime
from datetime import datetime
now=datetime.now()
import pprint
start = 1582150894
span = 2 * 365 * 84000

difference = 0
last_difference = 0
i = start

tdiff=[]
js_filename='stix.datetime.spice.js'
cpp_filename='SPICEData.cc'
ch_filename='SPICEData.h'
T0=0

while i < span + start:
    obt = stix_datetime.unix2scet(i)
    difference = i - obt
    if abs(last_difference - difference) > 0.1:
        if T0==0:
            T0=i
        print(i, stix_datetime.unix2utc(i), difference)
        tdiff.append([i, difference, stix_datetime.unix2utc(i)])
        last_difference = difference
    i += 3600

with open(js_filename,'w') as fjs:
    fjs.write('//generated by obt2unix_difference.py  on {}\n'.format(now.isoformat()))
    fjs.write('//#unix, differences, utc\n')
    fjs.write('UNIX_T0={};\n'.format(T0))
    fjs.write('OBT_UNIX_DIFF={\n')
    fjs.write('unix:[{}],'.format( ','.join([str(x[0]-T0) for x in tdiff])))
    fjs.write('diff:[{}],'.format( ','.join([str(x[1]) for x in tdiff])))
    fjs.write('};\n')
    print('{} has been generated'.format(js_filename))
    print('Please copy this file to web/static/js/')

    fjs.close()

with open(cpp_filename,'w') as fjs:
    fjs.write('//generated by obt2unix_difference.py  on {}\n'.format(now.isoformat()))
    fjs.write('//#unix, differences\n')
    fjs.write('UNIX_T0={};\n'.format(T0))
    fjs.write('int UNIX_TIME={\n')
    fjs.write('{}'.format( ','.join([str(x[0]-T0) for x in tdiff])))
    fjs.write('};\n')
    fjs.write('double UNIX_TO_OBT_DIFF={\n')
    fjs.write('{}'.format( ','.join([str(x[1]) for x in tdiff])))
    fjs.write('};\n')
    print('{} has been generated'.format(js_filename))
    print('Please copy this file to web/static/js/')

    fjs.close()









