update PCF set PCF_WIDTH=16 where PCF_NAME="NIX00123";
update PCF set PCF_WIDTH=8 where PCF_NAME="ZZPAD008";
update PCF set PCF_WIDTH=16 where PCF_NAME='ZZPAD016';
update PCF set PCF_WIDTH=24 where PCF_NAME='ZZPAD024';
update PCF set PCF_WIDTH=32 where PCF_NAME='ZZPAD032';
update SW_PARA set SW_DESCR="Pixel 7" where SCOS_NAME='NIXD0410';
update SW_PARA set SW_DESCR="Pixel 3" where SCOS_NAME="NIXD0411";
update SW_PARA set SW_DESCR="TH - Ch 2" where SCOS_NAME="NIXD0412";
update SW_PARA set SW_DESCR="Pixel 11" where SCOS_NAME="NIXD0413";
update SW_PARA set SW_DESCR="TH - Ch 4" where SCOS_NAME="NIXD0414";
update SW_PARA set SW_DESCR="Pixel 6" where SCOS_NAME="NIXD0415";
update SW_PARA set SW_DESCR="TH - Ch 6" where SCOS_NAME="NIXD0416";
update SW_PARA set SW_DESCR="TH - Ch 7" where SCOS_NAME="NIXD0417";
update SW_PARA set SW_DESCR="Pixel 2" where SCOS_NAME="NIXD0418";
update SW_PARA set SW_DESCR="TH - Ch 9" where SCOS_NAME="NIXD0419";
update SW_PARA set SW_DESCR="TH - Ch 10" where SCOS_NAME="NIXD0420";
update SW_PARA set SW_DESCR="Pixel 10" where SCOS_NAME="NIXD0421";
update SW_PARA set SW_DESCR="TH - Ch 12" where SCOS_NAME="NIXD0422";
update SW_PARA set SW_DESCR="TH - Ch 13" where SCOS_NAME="NIXD0423";
update SW_PARA set SW_DESCR="TH - Ch 14" where SCOS_NAME="NIXD0424";
update SW_PARA set SW_DESCR="Pixel 1" where SCOS_NAME="NIXD0425";
update SW_PARA set SW_DESCR="TH - Ch 16" where SCOS_NAME="NIXD0426";
update SW_PARA set SW_DESCR="TH - Ch 17" where SCOS_NAME="NIXD0427";
update SW_PARA set SW_DESCR="Pixel 5" where SCOS_NAME="NIXD0428";
update SW_PARA set SW_DESCR="TH - Ch 19" where SCOS_NAME="NIXD0429";
update SW_PARA set SW_DESCR="TH - Ch 20" where SCOS_NAME="NIXD0430";
update SW_PARA set SW_DESCR="Pixel 9" where SCOS_NAME="NIXD0431";
update SW_PARA set SW_DESCR="TH - Ch 22" where SCOS_NAME="NIXD0432";
update SW_PARA set SW_DESCR="TH - Ch 23" where SCOS_NAME="NIXD0433";
update SW_PARA set SW_DESCR="TH - Ch 24" where SCOS_NAME="NIXD0434";
update SW_PARA set SW_DESCR="TH - Ch 25" where SCOS_NAME="NIXD0435";
update SW_PARA set SW_DESCR="Pixel 0" where SCOS_NAME="NIXD0436";
update SW_PARA set SW_DESCR="TH - Ch 27" where SCOS_NAME="NIXD0437";
update SW_PARA set SW_DESCR="TH - Ch 28" where SCOS_NAME="NIXD0438";
update SW_PARA set SW_DESCR="Pixel 4" where SCOS_NAME="NIXD0439";
update SW_PARA set SW_DESCR="Pixel 8" where SCOS_NAME="NIXD0440";
update SW_PARA set SW_DESCR="Guardring" where SCOS_NAME="NIXD0441";
update SW_PARA set SW_DESCR="Pixel 7" where SCOS_NAME="PIX00122";
update SW_PARA set SW_DESCR="Pixel 3" where SCOS_NAME="PIX00123";
update SW_PARA set SW_DESCR="TH - Ch 2" where SCOS_NAME="PIX00124";
update SW_PARA set SW_DESCR="Pixel 11" where SCOS_NAME="PIX00125";
update SW_PARA set SW_DESCR="TH - Ch 4" where SCOS_NAME="PIX00126";
update SW_PARA set SW_DESCR="Pixel 6" where SCOS_NAME="PIX00127";
update SW_PARA set SW_DESCR="TH - Ch 6" where SCOS_NAME="PIX00128";
update SW_PARA set SW_DESCR="TH - Ch 7" where SCOS_NAME="PIX00129";
update SW_PARA set SW_DESCR="Pixel 2" where SCOS_NAME="PIX00130";
update SW_PARA set SW_DESCR="TH - Ch 9" where SCOS_NAME="PIX00131";
update SW_PARA set SW_DESCR="TH - Ch 10" where SCOS_NAME="PIX00132";
update SW_PARA set SW_DESCR="Pixel 10" where SCOS_NAME="PIX00133";
update SW_PARA set SW_DESCR="TH - Ch 12" where SCOS_NAME="PIX00134";
update SW_PARA set SW_DESCR="TH - Ch 13" where SCOS_NAME="PIX00135";
update SW_PARA set SW_DESCR="TH - Ch 14" where SCOS_NAME="PIX00136";
update SW_PARA set SW_DESCR="Pixel 1" where SCOS_NAME="PIX00137";
update SW_PARA set SW_DESCR="TH - Ch 16" where SCOS_NAME="PIX00138";
update SW_PARA set SW_DESCR="TH - Ch 17" where SCOS_NAME="PIX00139";
update SW_PARA set SW_DESCR="Pixel 5" where SCOS_NAME="PIX00140";
update SW_PARA set SW_DESCR="TH - Ch 19" where SCOS_NAME="PIX00141";
update SW_PARA set SW_DESCR="TH - Ch 20" where SCOS_NAME="PIX00142";
update SW_PARA set SW_DESCR="Pixel 9" where SCOS_NAME="PIX00143";
update SW_PARA set SW_DESCR="TH - Ch 22" where SCOS_NAME="PIX00144";
update SW_PARA set SW_DESCR="TH - Ch 23" where SCOS_NAME="PIX00145";
update SW_PARA set SW_DESCR="TH - Ch 24" where SCOS_NAME="PIX00146";
update SW_PARA set SW_DESCR="TH - Ch 25" where SCOS_NAME="PIX00147";
update SW_PARA set SW_DESCR="Pixel 0" where SCOS_NAME="PIX00148";
update SW_PARA set SW_DESCR="TH - Ch 27" where SCOS_NAME="PIX00149";
update SW_PARA set SW_DESCR="TH - Ch 28" where SCOS_NAME="PIX00150";
update SW_PARA set SW_DESCR="Pixel 4" where SCOS_NAME="PIX00151";
update SW_PARA set SW_DESCR="Pixel 8" where SCOS_NAME="PIX00152";
update SW_PARA set SW_DESCR="Guardring" where SCOS_NAME="PIX00153";


drop table if exists IDB;
create table IDB(
creation_datetime  datetime,
version  varchar(64) not null
);
insert into IDB (creation_datetime, version) values (current_timestamp, '2.26.28');

